// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v5.28.3
// source: proto/player/v1/player.proto

package playerv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PlayerService_RegisterPlayer_FullMethodName           = "/player.v1.PlayerService/RegisterPlayer"
	PlayerService_VerifyOTP_FullMethodName                = "/player.v1.PlayerService/VerifyOTP"
	PlayerService_ResendOTP_FullMethodName                = "/player.v1.PlayerService/ResendOTP"
	PlayerService_Login_FullMethodName                    = "/player.v1.PlayerService/Login"
	PlayerService_RefreshToken_FullMethodName             = "/player.v1.PlayerService/RefreshToken"
	PlayerService_Logout_FullMethodName                   = "/player.v1.PlayerService/Logout"
	PlayerService_USSDRegister_FullMethodName             = "/player.v1.PlayerService/USSDRegister"
	PlayerService_USSDLogin_FullMethodName                = "/player.v1.PlayerService/USSDLogin"
	PlayerService_RequestPasswordReset_FullMethodName     = "/player.v1.PlayerService/RequestPasswordReset"
	PlayerService_ValidatePasswordResetOTP_FullMethodName = "/player.v1.PlayerService/ValidatePasswordResetOTP"
	PlayerService_ConfirmPasswordReset_FullMethodName     = "/player.v1.PlayerService/ConfirmPasswordReset"
	PlayerService_ResendPasswordResetOTP_FullMethodName   = "/player.v1.PlayerService/ResendPasswordResetOTP"
	PlayerService_GetProfile_FullMethodName               = "/player.v1.PlayerService/GetProfile"
	PlayerService_UpdateProfile_FullMethodName            = "/player.v1.PlayerService/UpdateProfile"
	PlayerService_ChangePassword_FullMethodName           = "/player.v1.PlayerService/ChangePassword"
	PlayerService_UpdateMobileMoneyPhone_FullMethodName   = "/player.v1.PlayerService/UpdateMobileMoneyPhone"
	PlayerService_InitiateDeposit_FullMethodName          = "/player.v1.PlayerService/InitiateDeposit"
	PlayerService_InitiateWithdrawal_FullMethodName       = "/player.v1.PlayerService/InitiateWithdrawal"
	PlayerService_GetTransactionHistory_FullMethodName    = "/player.v1.PlayerService/GetTransactionHistory"
	PlayerService_GetWalletBalance_FullMethodName         = "/player.v1.PlayerService/GetWalletBalance"
	PlayerService_GetPlayerByID_FullMethodName            = "/player.v1.PlayerService/GetPlayerByID"
	PlayerService_SearchPlayers_FullMethodName            = "/player.v1.PlayerService/SearchPlayers"
	PlayerService_SuspendPlayer_FullMethodName            = "/player.v1.PlayerService/SuspendPlayer"
	PlayerService_ActivatePlayer_FullMethodName           = "/player.v1.PlayerService/ActivatePlayer"
	PlayerService_SubmitFeedback_FullMethodName           = "/player.v1.PlayerService/SubmitFeedback"
)

// PlayerServiceClient is the client API for PlayerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PlayerServiceClient interface {
	// Standard Authentication (Mobile/Web/Telegram)
	RegisterPlayer(ctx context.Context, in *RegisterPlayerRequest, opts ...grpc.CallOption) (*RegisterPlayerResponse, error)
	VerifyOTP(ctx context.Context, in *VerifyOTPRequest, opts ...grpc.CallOption) (*VerifyOTPResponse, error)
	ResendOTP(ctx context.Context, in *ResendOTPRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error)
	RefreshToken(ctx context.Context, in *RefreshTokenRequest, opts ...grpc.CallOption) (*RefreshTokenResponse, error)
	Logout(ctx context.Context, in *LogoutRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// USSD Authentication (No OTP required)
	USSDRegister(ctx context.Context, in *USSDRegisterRequest, opts ...grpc.CallOption) (*USSDAuthResponse, error)
	USSDLogin(ctx context.Context, in *USSDLoginRequest, opts ...grpc.CallOption) (*USSDAuthResponse, error)
	// Password Reset Flow
	RequestPasswordReset(ctx context.Context, in *RequestPasswordResetRequest, opts ...grpc.CallOption) (*RequestPasswordResetResponse, error)
	ValidatePasswordResetOTP(ctx context.Context, in *ValidatePasswordResetOTPRequest, opts ...grpc.CallOption) (*ValidatePasswordResetOTPResponse, error)
	ConfirmPasswordReset(ctx context.Context, in *ConfirmPasswordResetRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	ResendPasswordResetOTP(ctx context.Context, in *ResendPasswordResetOTPRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Profile Management
	GetProfile(ctx context.Context, in *GetProfileRequest, opts ...grpc.CallOption) (*PlayerProfile, error)
	UpdateProfile(ctx context.Context, in *UpdateProfileRequest, opts ...grpc.CallOption) (*PlayerProfile, error)
	ChangePassword(ctx context.Context, in *ChangePasswordRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	UpdateMobileMoneyPhone(ctx context.Context, in *UpdatePhoneRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Wallet Operations (delegates to Payment/Wallet Services)
	InitiateDeposit(ctx context.Context, in *DepositRequest, opts ...grpc.CallOption) (*DepositResponse, error)
	InitiateWithdrawal(ctx context.Context, in *WithdrawalRequest, opts ...grpc.CallOption) (*WithdrawalResponse, error)
	GetTransactionHistory(ctx context.Context, in *TransactionHistoryRequest, opts ...grpc.CallOption) (*TransactionHistoryResponse, error)
	GetWalletBalance(ctx context.Context, in *WalletBalanceRequest, opts ...grpc.CallOption) (*WalletBalanceResponse, error)
	// Admin Operations
	GetPlayerByID(ctx context.Context, in *GetPlayerByIDRequest, opts ...grpc.CallOption) (*PlayerProfile, error)
	SearchPlayers(ctx context.Context, in *SearchPlayersRequest, opts ...grpc.CallOption) (*SearchPlayersResponse, error)
	SuspendPlayer(ctx context.Context, in *SuspendPlayerRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	ActivatePlayer(ctx context.Context, in *ActivatePlayerRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	SubmitFeedback(ctx context.Context, in *SubmitFeedbackRequest, opts ...grpc.CallOption) (*SubmitFeedbackResponse, error)
}

type playerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPlayerServiceClient(cc grpc.ClientConnInterface) PlayerServiceClient {
	return &playerServiceClient{cc}
}

func (c *playerServiceClient) RegisterPlayer(ctx context.Context, in *RegisterPlayerRequest, opts ...grpc.CallOption) (*RegisterPlayerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterPlayerResponse)
	err := c.cc.Invoke(ctx, PlayerService_RegisterPlayer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playerServiceClient) VerifyOTP(ctx context.Context, in *VerifyOTPRequest, opts ...grpc.CallOption) (*VerifyOTPResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VerifyOTPResponse)
	err := c.cc.Invoke(ctx, PlayerService_VerifyOTP_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playerServiceClient) ResendOTP(ctx context.Context, in *ResendOTPRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, PlayerService_ResendOTP_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playerServiceClient) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoginResponse)
	err := c.cc.Invoke(ctx, PlayerService_Login_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playerServiceClient) RefreshToken(ctx context.Context, in *RefreshTokenRequest, opts ...grpc.CallOption) (*RefreshTokenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RefreshTokenResponse)
	err := c.cc.Invoke(ctx, PlayerService_RefreshToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playerServiceClient) Logout(ctx context.Context, in *LogoutRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, PlayerService_Logout_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playerServiceClient) USSDRegister(ctx context.Context, in *USSDRegisterRequest, opts ...grpc.CallOption) (*USSDAuthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(USSDAuthResponse)
	err := c.cc.Invoke(ctx, PlayerService_USSDRegister_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playerServiceClient) USSDLogin(ctx context.Context, in *USSDLoginRequest, opts ...grpc.CallOption) (*USSDAuthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(USSDAuthResponse)
	err := c.cc.Invoke(ctx, PlayerService_USSDLogin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playerServiceClient) RequestPasswordReset(ctx context.Context, in *RequestPasswordResetRequest, opts ...grpc.CallOption) (*RequestPasswordResetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RequestPasswordResetResponse)
	err := c.cc.Invoke(ctx, PlayerService_RequestPasswordReset_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playerServiceClient) ValidatePasswordResetOTP(ctx context.Context, in *ValidatePasswordResetOTPRequest, opts ...grpc.CallOption) (*ValidatePasswordResetOTPResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ValidatePasswordResetOTPResponse)
	err := c.cc.Invoke(ctx, PlayerService_ValidatePasswordResetOTP_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playerServiceClient) ConfirmPasswordReset(ctx context.Context, in *ConfirmPasswordResetRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, PlayerService_ConfirmPasswordReset_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playerServiceClient) ResendPasswordResetOTP(ctx context.Context, in *ResendPasswordResetOTPRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, PlayerService_ResendPasswordResetOTP_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playerServiceClient) GetProfile(ctx context.Context, in *GetProfileRequest, opts ...grpc.CallOption) (*PlayerProfile, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PlayerProfile)
	err := c.cc.Invoke(ctx, PlayerService_GetProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playerServiceClient) UpdateProfile(ctx context.Context, in *UpdateProfileRequest, opts ...grpc.CallOption) (*PlayerProfile, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PlayerProfile)
	err := c.cc.Invoke(ctx, PlayerService_UpdateProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playerServiceClient) ChangePassword(ctx context.Context, in *ChangePasswordRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, PlayerService_ChangePassword_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playerServiceClient) UpdateMobileMoneyPhone(ctx context.Context, in *UpdatePhoneRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, PlayerService_UpdateMobileMoneyPhone_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playerServiceClient) InitiateDeposit(ctx context.Context, in *DepositRequest, opts ...grpc.CallOption) (*DepositResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DepositResponse)
	err := c.cc.Invoke(ctx, PlayerService_InitiateDeposit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playerServiceClient) InitiateWithdrawal(ctx context.Context, in *WithdrawalRequest, opts ...grpc.CallOption) (*WithdrawalResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WithdrawalResponse)
	err := c.cc.Invoke(ctx, PlayerService_InitiateWithdrawal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playerServiceClient) GetTransactionHistory(ctx context.Context, in *TransactionHistoryRequest, opts ...grpc.CallOption) (*TransactionHistoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TransactionHistoryResponse)
	err := c.cc.Invoke(ctx, PlayerService_GetTransactionHistory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playerServiceClient) GetWalletBalance(ctx context.Context, in *WalletBalanceRequest, opts ...grpc.CallOption) (*WalletBalanceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WalletBalanceResponse)
	err := c.cc.Invoke(ctx, PlayerService_GetWalletBalance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playerServiceClient) GetPlayerByID(ctx context.Context, in *GetPlayerByIDRequest, opts ...grpc.CallOption) (*PlayerProfile, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PlayerProfile)
	err := c.cc.Invoke(ctx, PlayerService_GetPlayerByID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playerServiceClient) SearchPlayers(ctx context.Context, in *SearchPlayersRequest, opts ...grpc.CallOption) (*SearchPlayersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchPlayersResponse)
	err := c.cc.Invoke(ctx, PlayerService_SearchPlayers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playerServiceClient) SuspendPlayer(ctx context.Context, in *SuspendPlayerRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, PlayerService_SuspendPlayer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playerServiceClient) ActivatePlayer(ctx context.Context, in *ActivatePlayerRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, PlayerService_ActivatePlayer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playerServiceClient) SubmitFeedback(ctx context.Context, in *SubmitFeedbackRequest, opts ...grpc.CallOption) (*SubmitFeedbackResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubmitFeedbackResponse)
	err := c.cc.Invoke(ctx, PlayerService_SubmitFeedback_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PlayerServiceServer is the server API for PlayerService service.
// All implementations must embed UnimplementedPlayerServiceServer
// for forward compatibility.
type PlayerServiceServer interface {
	// Standard Authentication (Mobile/Web/Telegram)
	RegisterPlayer(context.Context, *RegisterPlayerRequest) (*RegisterPlayerResponse, error)
	VerifyOTP(context.Context, *VerifyOTPRequest) (*VerifyOTPResponse, error)
	ResendOTP(context.Context, *ResendOTPRequest) (*emptypb.Empty, error)
	Login(context.Context, *LoginRequest) (*LoginResponse, error)
	RefreshToken(context.Context, *RefreshTokenRequest) (*RefreshTokenResponse, error)
	Logout(context.Context, *LogoutRequest) (*emptypb.Empty, error)
	// USSD Authentication (No OTP required)
	USSDRegister(context.Context, *USSDRegisterRequest) (*USSDAuthResponse, error)
	USSDLogin(context.Context, *USSDLoginRequest) (*USSDAuthResponse, error)
	// Password Reset Flow
	RequestPasswordReset(context.Context, *RequestPasswordResetRequest) (*RequestPasswordResetResponse, error)
	ValidatePasswordResetOTP(context.Context, *ValidatePasswordResetOTPRequest) (*ValidatePasswordResetOTPResponse, error)
	ConfirmPasswordReset(context.Context, *ConfirmPasswordResetRequest) (*emptypb.Empty, error)
	ResendPasswordResetOTP(context.Context, *ResendPasswordResetOTPRequest) (*emptypb.Empty, error)
	// Profile Management
	GetProfile(context.Context, *GetProfileRequest) (*PlayerProfile, error)
	UpdateProfile(context.Context, *UpdateProfileRequest) (*PlayerProfile, error)
	ChangePassword(context.Context, *ChangePasswordRequest) (*emptypb.Empty, error)
	UpdateMobileMoneyPhone(context.Context, *UpdatePhoneRequest) (*emptypb.Empty, error)
	// Wallet Operations (delegates to Payment/Wallet Services)
	InitiateDeposit(context.Context, *DepositRequest) (*DepositResponse, error)
	InitiateWithdrawal(context.Context, *WithdrawalRequest) (*WithdrawalResponse, error)
	GetTransactionHistory(context.Context, *TransactionHistoryRequest) (*TransactionHistoryResponse, error)
	GetWalletBalance(context.Context, *WalletBalanceRequest) (*WalletBalanceResponse, error)
	// Admin Operations
	GetPlayerByID(context.Context, *GetPlayerByIDRequest) (*PlayerProfile, error)
	SearchPlayers(context.Context, *SearchPlayersRequest) (*SearchPlayersResponse, error)
	SuspendPlayer(context.Context, *SuspendPlayerRequest) (*emptypb.Empty, error)
	ActivatePlayer(context.Context, *ActivatePlayerRequest) (*emptypb.Empty, error)
	SubmitFeedback(context.Context, *SubmitFeedbackRequest) (*SubmitFeedbackResponse, error)
	mustEmbedUnimplementedPlayerServiceServer()
}

// UnimplementedPlayerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPlayerServiceServer struct{}

func (UnimplementedPlayerServiceServer) RegisterPlayer(context.Context, *RegisterPlayerRequest) (*RegisterPlayerResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterPlayer not implemented")
}
func (UnimplementedPlayerServiceServer) VerifyOTP(context.Context, *VerifyOTPRequest) (*VerifyOTPResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method VerifyOTP not implemented")
}
func (UnimplementedPlayerServiceServer) ResendOTP(context.Context, *ResendOTPRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method ResendOTP not implemented")
}
func (UnimplementedPlayerServiceServer) Login(context.Context, *LoginRequest) (*LoginResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Login not implemented")
}
func (UnimplementedPlayerServiceServer) RefreshToken(context.Context, *RefreshTokenRequest) (*RefreshTokenResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RefreshToken not implemented")
}
func (UnimplementedPlayerServiceServer) Logout(context.Context, *LogoutRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method Logout not implemented")
}
func (UnimplementedPlayerServiceServer) USSDRegister(context.Context, *USSDRegisterRequest) (*USSDAuthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method USSDRegister not implemented")
}
func (UnimplementedPlayerServiceServer) USSDLogin(context.Context, *USSDLoginRequest) (*USSDAuthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method USSDLogin not implemented")
}
func (UnimplementedPlayerServiceServer) RequestPasswordReset(context.Context, *RequestPasswordResetRequest) (*RequestPasswordResetResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RequestPasswordReset not implemented")
}
func (UnimplementedPlayerServiceServer) ValidatePasswordResetOTP(context.Context, *ValidatePasswordResetOTPRequest) (*ValidatePasswordResetOTPResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ValidatePasswordResetOTP not implemented")
}
func (UnimplementedPlayerServiceServer) ConfirmPasswordReset(context.Context, *ConfirmPasswordResetRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method ConfirmPasswordReset not implemented")
}
func (UnimplementedPlayerServiceServer) ResendPasswordResetOTP(context.Context, *ResendPasswordResetOTPRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method ResendPasswordResetOTP not implemented")
}
func (UnimplementedPlayerServiceServer) GetProfile(context.Context, *GetProfileRequest) (*PlayerProfile, error) {
	return nil, status.Error(codes.Unimplemented, "method GetProfile not implemented")
}
func (UnimplementedPlayerServiceServer) UpdateProfile(context.Context, *UpdateProfileRequest) (*PlayerProfile, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateProfile not implemented")
}
func (UnimplementedPlayerServiceServer) ChangePassword(context.Context, *ChangePasswordRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method ChangePassword not implemented")
}
func (UnimplementedPlayerServiceServer) UpdateMobileMoneyPhone(context.Context, *UpdatePhoneRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateMobileMoneyPhone not implemented")
}
func (UnimplementedPlayerServiceServer) InitiateDeposit(context.Context, *DepositRequest) (*DepositResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method InitiateDeposit not implemented")
}
func (UnimplementedPlayerServiceServer) InitiateWithdrawal(context.Context, *WithdrawalRequest) (*WithdrawalResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method InitiateWithdrawal not implemented")
}
func (UnimplementedPlayerServiceServer) GetTransactionHistory(context.Context, *TransactionHistoryRequest) (*TransactionHistoryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTransactionHistory not implemented")
}
func (UnimplementedPlayerServiceServer) GetWalletBalance(context.Context, *WalletBalanceRequest) (*WalletBalanceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetWalletBalance not implemented")
}
func (UnimplementedPlayerServiceServer) GetPlayerByID(context.Context, *GetPlayerByIDRequest) (*PlayerProfile, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPlayerByID not implemented")
}
func (UnimplementedPlayerServiceServer) SearchPlayers(context.Context, *SearchPlayersRequest) (*SearchPlayersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SearchPlayers not implemented")
}
func (UnimplementedPlayerServiceServer) SuspendPlayer(context.Context, *SuspendPlayerRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method SuspendPlayer not implemented")
}
func (UnimplementedPlayerServiceServer) ActivatePlayer(context.Context, *ActivatePlayerRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method ActivatePlayer not implemented")
}
func (UnimplementedPlayerServiceServer) SubmitFeedback(context.Context, *SubmitFeedbackRequest) (*SubmitFeedbackResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SubmitFeedback not implemented")
}
func (UnimplementedPlayerServiceServer) mustEmbedUnimplementedPlayerServiceServer() {}
func (UnimplementedPlayerServiceServer) testEmbeddedByValue()                       {}

// UnsafePlayerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PlayerServiceServer will
// result in compilation errors.
type UnsafePlayerServiceServer interface {
	mustEmbedUnimplementedPlayerServiceServer()
}

func RegisterPlayerServiceServer(s grpc.ServiceRegistrar, srv PlayerServiceServer) {
	// If the following call panics, it indicates UnimplementedPlayerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PlayerService_ServiceDesc, srv)
}

func _PlayerService_RegisterPlayer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterPlayerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlayerServiceServer).RegisterPlayer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlayerService_RegisterPlayer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlayerServiceServer).RegisterPlayer(ctx, req.(*RegisterPlayerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlayerService_VerifyOTP_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyOTPRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlayerServiceServer).VerifyOTP(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlayerService_VerifyOTP_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlayerServiceServer).VerifyOTP(ctx, req.(*VerifyOTPRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlayerService_ResendOTP_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResendOTPRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlayerServiceServer).ResendOTP(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlayerService_ResendOTP_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlayerServiceServer).ResendOTP(ctx, req.(*ResendOTPRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlayerService_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlayerServiceServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlayerService_Login_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlayerServiceServer).Login(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlayerService_RefreshToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RefreshTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlayerServiceServer).RefreshToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlayerService_RefreshToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlayerServiceServer).RefreshToken(ctx, req.(*RefreshTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlayerService_Logout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogoutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlayerServiceServer).Logout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlayerService_Logout_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlayerServiceServer).Logout(ctx, req.(*LogoutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlayerService_USSDRegister_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(USSDRegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlayerServiceServer).USSDRegister(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlayerService_USSDRegister_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlayerServiceServer).USSDRegister(ctx, req.(*USSDRegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlayerService_USSDLogin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(USSDLoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlayerServiceServer).USSDLogin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlayerService_USSDLogin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlayerServiceServer).USSDLogin(ctx, req.(*USSDLoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlayerService_RequestPasswordReset_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestPasswordResetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlayerServiceServer).RequestPasswordReset(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlayerService_RequestPasswordReset_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlayerServiceServer).RequestPasswordReset(ctx, req.(*RequestPasswordResetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlayerService_ValidatePasswordResetOTP_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidatePasswordResetOTPRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlayerServiceServer).ValidatePasswordResetOTP(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlayerService_ValidatePasswordResetOTP_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlayerServiceServer).ValidatePasswordResetOTP(ctx, req.(*ValidatePasswordResetOTPRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlayerService_ConfirmPasswordReset_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfirmPasswordResetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlayerServiceServer).ConfirmPasswordReset(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlayerService_ConfirmPasswordReset_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlayerServiceServer).ConfirmPasswordReset(ctx, req.(*ConfirmPasswordResetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlayerService_ResendPasswordResetOTP_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResendPasswordResetOTPRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlayerServiceServer).ResendPasswordResetOTP(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlayerService_ResendPasswordResetOTP_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlayerServiceServer).ResendPasswordResetOTP(ctx, req.(*ResendPasswordResetOTPRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlayerService_GetProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlayerServiceServer).GetProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlayerService_GetProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlayerServiceServer).GetProfile(ctx, req.(*GetProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlayerService_UpdateProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlayerServiceServer).UpdateProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlayerService_UpdateProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlayerServiceServer).UpdateProfile(ctx, req.(*UpdateProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlayerService_ChangePassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChangePasswordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlayerServiceServer).ChangePassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlayerService_ChangePassword_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlayerServiceServer).ChangePassword(ctx, req.(*ChangePasswordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlayerService_UpdateMobileMoneyPhone_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdatePhoneRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlayerServiceServer).UpdateMobileMoneyPhone(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlayerService_UpdateMobileMoneyPhone_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlayerServiceServer).UpdateMobileMoneyPhone(ctx, req.(*UpdatePhoneRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlayerService_InitiateDeposit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DepositRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlayerServiceServer).InitiateDeposit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlayerService_InitiateDeposit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlayerServiceServer).InitiateDeposit(ctx, req.(*DepositRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlayerService_InitiateWithdrawal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WithdrawalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlayerServiceServer).InitiateWithdrawal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlayerService_InitiateWithdrawal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlayerServiceServer).InitiateWithdrawal(ctx, req.(*WithdrawalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlayerService_GetTransactionHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TransactionHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlayerServiceServer).GetTransactionHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlayerService_GetTransactionHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlayerServiceServer).GetTransactionHistory(ctx, req.(*TransactionHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlayerService_GetWalletBalance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WalletBalanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlayerServiceServer).GetWalletBalance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlayerService_GetWalletBalance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlayerServiceServer).GetWalletBalance(ctx, req.(*WalletBalanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlayerService_GetPlayerByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPlayerByIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlayerServiceServer).GetPlayerByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlayerService_GetPlayerByID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlayerServiceServer).GetPlayerByID(ctx, req.(*GetPlayerByIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlayerService_SearchPlayers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchPlayersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlayerServiceServer).SearchPlayers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlayerService_SearchPlayers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlayerServiceServer).SearchPlayers(ctx, req.(*SearchPlayersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlayerService_SuspendPlayer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SuspendPlayerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlayerServiceServer).SuspendPlayer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlayerService_SuspendPlayer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlayerServiceServer).SuspendPlayer(ctx, req.(*SuspendPlayerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlayerService_ActivatePlayer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ActivatePlayerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlayerServiceServer).ActivatePlayer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlayerService_ActivatePlayer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlayerServiceServer).ActivatePlayer(ctx, req.(*ActivatePlayerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlayerService_SubmitFeedback_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitFeedbackRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlayerServiceServer).SubmitFeedback(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlayerService_SubmitFeedback_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlayerServiceServer).SubmitFeedback(ctx, req.(*SubmitFeedbackRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PlayerService_ServiceDesc is the grpc.ServiceDesc for PlayerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PlayerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "player.v1.PlayerService",
	HandlerType: (*PlayerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterPlayer",
			Handler:    _PlayerService_RegisterPlayer_Handler,
		},
		{
			MethodName: "VerifyOTP",
			Handler:    _PlayerService_VerifyOTP_Handler,
		},
		{
			MethodName: "ResendOTP",
			Handler:    _PlayerService_ResendOTP_Handler,
		},
		{
			MethodName: "Login",
			Handler:    _PlayerService_Login_Handler,
		},
		{
			MethodName: "RefreshToken",
			Handler:    _PlayerService_RefreshToken_Handler,
		},
		{
			MethodName: "Logout",
			Handler:    _PlayerService_Logout_Handler,
		},
		{
			MethodName: "USSDRegister",
			Handler:    _PlayerService_USSDRegister_Handler,
		},
		{
			MethodName: "USSDLogin",
			Handler:    _PlayerService_USSDLogin_Handler,
		},
		{
			MethodName: "RequestPasswordReset",
			Handler:    _PlayerService_RequestPasswordReset_Handler,
		},
		{
			MethodName: "ValidatePasswordResetOTP",
			Handler:    _PlayerService_ValidatePasswordResetOTP_Handler,
		},
		{
			MethodName: "ConfirmPasswordReset",
			Handler:    _PlayerService_ConfirmPasswordReset_Handler,
		},
		{
			MethodName: "ResendPasswordResetOTP",
			Handler:    _PlayerService_ResendPasswordResetOTP_Handler,
		},
		{
			MethodName: "GetProfile",
			Handler:    _PlayerService_GetProfile_Handler,
		},
		{
			MethodName: "UpdateProfile",
			Handler:    _PlayerService_UpdateProfile_Handler,
		},
		{
			MethodName: "ChangePassword",
			Handler:    _PlayerService_ChangePassword_Handler,
		},
		{
			MethodName: "UpdateMobileMoneyPhone",
			Handler:    _PlayerService_UpdateMobileMoneyPhone_Handler,
		},
		{
			MethodName: "InitiateDeposit",
			Handler:    _PlayerService_InitiateDeposit_Handler,
		},
		{
			MethodName: "InitiateWithdrawal",
			Handler:    _PlayerService_InitiateWithdrawal_Handler,
		},
		{
			MethodName: "GetTransactionHistory",
			Handler:    _PlayerService_GetTransactionHistory_Handler,
		},
		{
			MethodName: "GetWalletBalance",
			Handler:    _PlayerService_GetWalletBalance_Handler,
		},
		{
			MethodName: "GetPlayerByID",
			Handler:    _PlayerService_GetPlayerByID_Handler,
		},
		{
			MethodName: "SearchPlayers",
			Handler:    _PlayerService_SearchPlayers_Handler,
		},
		{
			MethodName: "SuspendPlayer",
			Handler:    _PlayerService_SuspendPlayer_Handler,
		},
		{
			MethodName: "ActivatePlayer",
			Handler:    _PlayerService_ActivatePlayer_Handler,
		},
		{
			MethodName: "SubmitFeedback",
			Handler:    _PlayerService_SubmitFeedback_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/player/v1/player.proto",
}
