/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WinsRouteImport } from './routes/wins'
import { Route as UssdSessionsRouteImport } from './routes/ussd-sessions'
import { Route as TransactionsRouteImport } from './routes/transactions'
import { Route as PlayersRouteImport } from './routes/players'
import { Route as LoginRouteImport } from './routes/login'
import { Route as GamesRouteImport } from './routes/games'
import { Route as DrawsRouteImport } from './routes/draws'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ScheduleScheduleIdRouteImport } from './routes/schedule.$scheduleId'
import { Route as GamesCreateRouteImport } from './routes/games/create'
import { Route as GameGameIdRouteImport } from './routes/game.$gameId'
import { Route as DrawDrawIdRouteImport } from './routes/draw.$drawId'
import { Route as ConfigWinnerSelectionRouteImport } from './routes/config/winner-selection'
import { Route as AdminWalletCreditsRouteImport } from './routes/admin.wallet-credits'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminTransactionsRouteImport } from './routes/admin.transactions'
import { Route as AdminRolesRouteImport } from './routes/admin.roles'
import { Route as AdminRetailersRouteImport } from './routes/admin.retailers'
import { Route as AdminPosTerminalsRouteImport } from './routes/admin.pos-terminals'
import { Route as AdminPlayersRouteImport } from './routes/admin.players'
import { Route as AdminPermissionsRouteImport } from './routes/admin.permissions'
import { Route as AdminAuditLogsRouteImport } from './routes/admin.audit-logs'
import { Route as AdminAgentsRouteImport } from './routes/admin.agents'
import { Route as AdminRetailerRetailerIdRouteImport } from './routes/admin.retailer.$retailerId'
import { Route as AdminPlayerPlayerIdRouteImport } from './routes/admin.player.$playerId'
import { Route as AdminAgentAgentIdRouteImport } from './routes/admin.agent.$agentId'

const WinsRoute = WinsRouteImport.update({
  id: '/wins',
  path: '/wins',
  getParentRoute: () => rootRouteImport,
} as any)
const UssdSessionsRoute = UssdSessionsRouteImport.update({
  id: '/ussd-sessions',
  path: '/ussd-sessions',
  getParentRoute: () => rootRouteImport,
} as any)
const TransactionsRoute = TransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayersRoute = PlayersRouteImport.update({
  id: '/players',
  path: '/players',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesRoute = GamesRouteImport.update({
  id: '/games',
  path: '/games',
  getParentRoute: () => rootRouteImport,
} as any)
const DrawsRoute = DrawsRouteImport.update({
  id: '/draws',
  path: '/draws',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ScheduleScheduleIdRoute = ScheduleScheduleIdRouteImport.update({
  id: '/schedule/$scheduleId',
  path: '/schedule/$scheduleId',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesCreateRoute = GamesCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => GamesRoute,
} as any)
const GameGameIdRoute = GameGameIdRouteImport.update({
  id: '/game/$gameId',
  path: '/game/$gameId',
  getParentRoute: () => rootRouteImport,
} as any)
const DrawDrawIdRoute = DrawDrawIdRouteImport.update({
  id: '/draw/$drawId',
  path: '/draw/$drawId',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfigWinnerSelectionRoute = ConfigWinnerSelectionRouteImport.update({
  id: '/config/winner-selection',
  path: '/config/winner-selection',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminWalletCreditsRoute = AdminWalletCreditsRouteImport.update({
  id: '/admin/wallet-credits',
  path: '/admin/wallet-credits',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTransactionsRoute = AdminTransactionsRouteImport.update({
  id: '/admin/transactions',
  path: '/admin/transactions',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRolesRoute = AdminRolesRouteImport.update({
  id: '/admin/roles',
  path: '/admin/roles',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRetailersRoute = AdminRetailersRouteImport.update({
  id: '/admin/retailers',
  path: '/admin/retailers',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPosTerminalsRoute = AdminPosTerminalsRouteImport.update({
  id: '/admin/pos-terminals',
  path: '/admin/pos-terminals',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPlayersRoute = AdminPlayersRouteImport.update({
  id: '/admin/players',
  path: '/admin/players',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPermissionsRoute = AdminPermissionsRouteImport.update({
  id: '/admin/permissions',
  path: '/admin/permissions',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuditLogsRoute = AdminAuditLogsRouteImport.update({
  id: '/admin/audit-logs',
  path: '/admin/audit-logs',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAgentsRoute = AdminAgentsRouteImport.update({
  id: '/admin/agents',
  path: '/admin/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRetailerRetailerIdRoute = AdminRetailerRetailerIdRouteImport.update({
  id: '/admin/retailer/$retailerId',
  path: '/admin/retailer/$retailerId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPlayerPlayerIdRoute = AdminPlayerPlayerIdRouteImport.update({
  id: '/admin/player/$playerId',
  path: '/admin/player/$playerId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAgentAgentIdRoute = AdminAgentAgentIdRouteImport.update({
  id: '/admin/agent/$agentId',
  path: '/admin/agent/$agentId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/draws': typeof DrawsRoute
  '/games': typeof GamesRouteWithChildren
  '/login': typeof LoginRoute
  '/players': typeof PlayersRoute
  '/transactions': typeof TransactionsRoute
  '/ussd-sessions': typeof UssdSessionsRoute
  '/wins': typeof WinsRoute
  '/admin/agents': typeof AdminAgentsRoute
  '/admin/audit-logs': typeof AdminAuditLogsRoute
  '/admin/permissions': typeof AdminPermissionsRoute
  '/admin/players': typeof AdminPlayersRoute
  '/admin/pos-terminals': typeof AdminPosTerminalsRoute
  '/admin/retailers': typeof AdminRetailersRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/transactions': typeof AdminTransactionsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/wallet-credits': typeof AdminWalletCreditsRoute
  '/config/winner-selection': typeof ConfigWinnerSelectionRoute
  '/draw/$drawId': typeof DrawDrawIdRoute
  '/game/$gameId': typeof GameGameIdRoute
  '/games/create': typeof GamesCreateRoute
  '/schedule/$scheduleId': typeof ScheduleScheduleIdRoute
  '/admin/agent/$agentId': typeof AdminAgentAgentIdRoute
  '/admin/player/$playerId': typeof AdminPlayerPlayerIdRoute
  '/admin/retailer/$retailerId': typeof AdminRetailerRetailerIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/draws': typeof DrawsRoute
  '/games': typeof GamesRouteWithChildren
  '/login': typeof LoginRoute
  '/players': typeof PlayersRoute
  '/transactions': typeof TransactionsRoute
  '/ussd-sessions': typeof UssdSessionsRoute
  '/wins': typeof WinsRoute
  '/admin/agents': typeof AdminAgentsRoute
  '/admin/audit-logs': typeof AdminAuditLogsRoute
  '/admin/permissions': typeof AdminPermissionsRoute
  '/admin/players': typeof AdminPlayersRoute
  '/admin/pos-terminals': typeof AdminPosTerminalsRoute
  '/admin/retailers': typeof AdminRetailersRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/transactions': typeof AdminTransactionsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/wallet-credits': typeof AdminWalletCreditsRoute
  '/config/winner-selection': typeof ConfigWinnerSelectionRoute
  '/draw/$drawId': typeof DrawDrawIdRoute
  '/game/$gameId': typeof GameGameIdRoute
  '/games/create': typeof GamesCreateRoute
  '/schedule/$scheduleId': typeof ScheduleScheduleIdRoute
  '/admin/agent/$agentId': typeof AdminAgentAgentIdRoute
  '/admin/player/$playerId': typeof AdminPlayerPlayerIdRoute
  '/admin/retailer/$retailerId': typeof AdminRetailerRetailerIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/draws': typeof DrawsRoute
  '/games': typeof GamesRouteWithChildren
  '/login': typeof LoginRoute
  '/players': typeof PlayersRoute
  '/transactions': typeof TransactionsRoute
  '/ussd-sessions': typeof UssdSessionsRoute
  '/wins': typeof WinsRoute
  '/admin/agents': typeof AdminAgentsRoute
  '/admin/audit-logs': typeof AdminAuditLogsRoute
  '/admin/permissions': typeof AdminPermissionsRoute
  '/admin/players': typeof AdminPlayersRoute
  '/admin/pos-terminals': typeof AdminPosTerminalsRoute
  '/admin/retailers': typeof AdminRetailersRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/transactions': typeof AdminTransactionsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/wallet-credits': typeof AdminWalletCreditsRoute
  '/config/winner-selection': typeof ConfigWinnerSelectionRoute
  '/draw/$drawId': typeof DrawDrawIdRoute
  '/game/$gameId': typeof GameGameIdRoute
  '/games/create': typeof GamesCreateRoute
  '/schedule/$scheduleId': typeof ScheduleScheduleIdRoute
  '/admin/agent/$agentId': typeof AdminAgentAgentIdRoute
  '/admin/player/$playerId': typeof AdminPlayerPlayerIdRoute
  '/admin/retailer/$retailerId': typeof AdminRetailerRetailerIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/draws'
    | '/games'
    | '/login'
    | '/players'
    | '/transactions'
    | '/ussd-sessions'
    | '/wins'
    | '/admin/agents'
    | '/admin/audit-logs'
    | '/admin/permissions'
    | '/admin/players'
    | '/admin/pos-terminals'
    | '/admin/retailers'
    | '/admin/roles'
    | '/admin/transactions'
    | '/admin/users'
    | '/admin/wallet-credits'
    | '/config/winner-selection'
    | '/draw/$drawId'
    | '/game/$gameId'
    | '/games/create'
    | '/schedule/$scheduleId'
    | '/admin/agent/$agentId'
    | '/admin/player/$playerId'
    | '/admin/retailer/$retailerId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/draws'
    | '/games'
    | '/login'
    | '/players'
    | '/transactions'
    | '/ussd-sessions'
    | '/wins'
    | '/admin/agents'
    | '/admin/audit-logs'
    | '/admin/permissions'
    | '/admin/players'
    | '/admin/pos-terminals'
    | '/admin/retailers'
    | '/admin/roles'
    | '/admin/transactions'
    | '/admin/users'
    | '/admin/wallet-credits'
    | '/config/winner-selection'
    | '/draw/$drawId'
    | '/game/$gameId'
    | '/games/create'
    | '/schedule/$scheduleId'
    | '/admin/agent/$agentId'
    | '/admin/player/$playerId'
    | '/admin/retailer/$retailerId'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/draws'
    | '/games'
    | '/login'
    | '/players'
    | '/transactions'
    | '/ussd-sessions'
    | '/wins'
    | '/admin/agents'
    | '/admin/audit-logs'
    | '/admin/permissions'
    | '/admin/players'
    | '/admin/pos-terminals'
    | '/admin/retailers'
    | '/admin/roles'
    | '/admin/transactions'
    | '/admin/users'
    | '/admin/wallet-credits'
    | '/config/winner-selection'
    | '/draw/$drawId'
    | '/game/$gameId'
    | '/games/create'
    | '/schedule/$scheduleId'
    | '/admin/agent/$agentId'
    | '/admin/player/$playerId'
    | '/admin/retailer/$retailerId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  DrawsRoute: typeof DrawsRoute
  GamesRoute: typeof GamesRouteWithChildren
  LoginRoute: typeof LoginRoute
  PlayersRoute: typeof PlayersRoute
  TransactionsRoute: typeof TransactionsRoute
  UssdSessionsRoute: typeof UssdSessionsRoute
  WinsRoute: typeof WinsRoute
  AdminAgentsRoute: typeof AdminAgentsRoute
  AdminAuditLogsRoute: typeof AdminAuditLogsRoute
  AdminPermissionsRoute: typeof AdminPermissionsRoute
  AdminPlayersRoute: typeof AdminPlayersRoute
  AdminPosTerminalsRoute: typeof AdminPosTerminalsRoute
  AdminRetailersRoute: typeof AdminRetailersRoute
  AdminRolesRoute: typeof AdminRolesRoute
  AdminTransactionsRoute: typeof AdminTransactionsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminWalletCreditsRoute: typeof AdminWalletCreditsRoute
  ConfigWinnerSelectionRoute: typeof ConfigWinnerSelectionRoute
  DrawDrawIdRoute: typeof DrawDrawIdRoute
  GameGameIdRoute: typeof GameGameIdRoute
  ScheduleScheduleIdRoute: typeof ScheduleScheduleIdRoute
  AdminAgentAgentIdRoute: typeof AdminAgentAgentIdRoute
  AdminPlayerPlayerIdRoute: typeof AdminPlayerPlayerIdRoute
  AdminRetailerRetailerIdRoute: typeof AdminRetailerRetailerIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wins': {
      id: '/wins'
      path: '/wins'
      fullPath: '/wins'
      preLoaderRoute: typeof WinsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ussd-sessions': {
      id: '/ussd-sessions'
      path: '/ussd-sessions'
      fullPath: '/ussd-sessions'
      preLoaderRoute: typeof UssdSessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transactions': {
      id: '/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof TransactionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/players': {
      id: '/players'
      path: '/players'
      fullPath: '/players'
      preLoaderRoute: typeof PlayersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games': {
      id: '/games'
      path: '/games'
      fullPath: '/games'
      preLoaderRoute: typeof GamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/draws': {
      id: '/draws'
      path: '/draws'
      fullPath: '/draws'
      preLoaderRoute: typeof DrawsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schedule/$scheduleId': {
      id: '/schedule/$scheduleId'
      path: '/schedule/$scheduleId'
      fullPath: '/schedule/$scheduleId'
      preLoaderRoute: typeof ScheduleScheduleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/create': {
      id: '/games/create'
      path: '/create'
      fullPath: '/games/create'
      preLoaderRoute: typeof GamesCreateRouteImport
      parentRoute: typeof GamesRoute
    }
    '/game/$gameId': {
      id: '/game/$gameId'
      path: '/game/$gameId'
      fullPath: '/game/$gameId'
      preLoaderRoute: typeof GameGameIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/draw/$drawId': {
      id: '/draw/$drawId'
      path: '/draw/$drawId'
      fullPath: '/draw/$drawId'
      preLoaderRoute: typeof DrawDrawIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/config/winner-selection': {
      id: '/config/winner-selection'
      path: '/config/winner-selection'
      fullPath: '/config/winner-selection'
      preLoaderRoute: typeof ConfigWinnerSelectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/wallet-credits': {
      id: '/admin/wallet-credits'
      path: '/admin/wallet-credits'
      fullPath: '/admin/wallet-credits'
      preLoaderRoute: typeof AdminWalletCreditsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/transactions': {
      id: '/admin/transactions'
      path: '/admin/transactions'
      fullPath: '/admin/transactions'
      preLoaderRoute: typeof AdminTransactionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/roles': {
      id: '/admin/roles'
      path: '/admin/roles'
      fullPath: '/admin/roles'
      preLoaderRoute: typeof AdminRolesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/retailers': {
      id: '/admin/retailers'
      path: '/admin/retailers'
      fullPath: '/admin/retailers'
      preLoaderRoute: typeof AdminRetailersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/pos-terminals': {
      id: '/admin/pos-terminals'
      path: '/admin/pos-terminals'
      fullPath: '/admin/pos-terminals'
      preLoaderRoute: typeof AdminPosTerminalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/players': {
      id: '/admin/players'
      path: '/admin/players'
      fullPath: '/admin/players'
      preLoaderRoute: typeof AdminPlayersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/permissions': {
      id: '/admin/permissions'
      path: '/admin/permissions'
      fullPath: '/admin/permissions'
      preLoaderRoute: typeof AdminPermissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/audit-logs': {
      id: '/admin/audit-logs'
      path: '/admin/audit-logs'
      fullPath: '/admin/audit-logs'
      preLoaderRoute: typeof AdminAuditLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/agents': {
      id: '/admin/agents'
      path: '/admin/agents'
      fullPath: '/admin/agents'
      preLoaderRoute: typeof AdminAgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/retailer/$retailerId': {
      id: '/admin/retailer/$retailerId'
      path: '/admin/retailer/$retailerId'
      fullPath: '/admin/retailer/$retailerId'
      preLoaderRoute: typeof AdminRetailerRetailerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/player/$playerId': {
      id: '/admin/player/$playerId'
      path: '/admin/player/$playerId'
      fullPath: '/admin/player/$playerId'
      preLoaderRoute: typeof AdminPlayerPlayerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/agent/$agentId': {
      id: '/admin/agent/$agentId'
      path: '/admin/agent/$agentId'
      fullPath: '/admin/agent/$agentId'
      preLoaderRoute: typeof AdminAgentAgentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface GamesRouteChildren {
  GamesCreateRoute: typeof GamesCreateRoute
}

const GamesRouteChildren: GamesRouteChildren = {
  GamesCreateRoute: GamesCreateRoute,
}

const GamesRouteWithChildren = GamesRoute._addFileChildren(GamesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  DrawsRoute: DrawsRoute,
  GamesRoute: GamesRouteWithChildren,
  LoginRoute: LoginRoute,
  PlayersRoute: PlayersRoute,
  TransactionsRoute: TransactionsRoute,
  UssdSessionsRoute: UssdSessionsRoute,
  WinsRoute: WinsRoute,
  AdminAgentsRoute: AdminAgentsRoute,
  AdminAuditLogsRoute: AdminAuditLogsRoute,
  AdminPermissionsRoute: AdminPermissionsRoute,
  AdminPlayersRoute: AdminPlayersRoute,
  AdminPosTerminalsRoute: AdminPosTerminalsRoute,
  AdminRetailersRoute: AdminRetailersRoute,
  AdminRolesRoute: AdminRolesRoute,
  AdminTransactionsRoute: AdminTransactionsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminWalletCreditsRoute: AdminWalletCreditsRoute,
  ConfigWinnerSelectionRoute: ConfigWinnerSelectionRoute,
  DrawDrawIdRoute: DrawDrawIdRoute,
  GameGameIdRoute: GameGameIdRoute,
  ScheduleScheduleIdRoute: ScheduleScheduleIdRoute,
  AdminAgentAgentIdRoute: AdminAgentAgentIdRoute,
  AdminPlayerPlayerIdRoute: AdminPlayerPlayerIdRoute,
  AdminRetailerRetailerIdRoute: AdminRetailerRetailerIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
