// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.6
// source: proto/game/v1/game.proto

package gamev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// GameServiceClient is the client API for GameService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GameServiceClient interface {
	// Game management
	CreateGame(ctx context.Context, in *CreateGameRequest, opts ...grpc.CallOption) (*CreateGameResponse, error)
	GetGame(ctx context.Context, in *GetGameRequest, opts ...grpc.CallOption) (*GetGameResponse, error)
	UpdateGame(ctx context.Context, in *UpdateGameRequest, opts ...grpc.CallOption) (*UpdateGameResponse, error)
	ListGames(ctx context.Context, in *ListGamesRequest, opts ...grpc.CallOption) (*ListGamesResponse, error)
	DeleteGame(ctx context.Context, in *DeleteGameRequest, opts ...grpc.CallOption) (*DeleteGameResponse, error)
	ActivateGame(ctx context.Context, in *ActivateGameRequest, opts ...grpc.CallOption) (*ActivateGameResponse, error)
	SuspendGame(ctx context.Context, in *SuspendGameRequest, opts ...grpc.CallOption) (*SuspendGameResponse, error)
	// Game rules management
	CreateGameRules(ctx context.Context, in *CreateGameRulesRequest, opts ...grpc.CallOption) (*CreateGameRulesResponse, error)
	GetGameRules(ctx context.Context, in *GetGameRulesRequest, opts ...grpc.CallOption) (*GetGameRulesResponse, error)
	UpdateGameRules(ctx context.Context, in *UpdateGameRulesRequest, opts ...grpc.CallOption) (*UpdateGameRulesResponse, error)
	// Prize structure management
	CreatePrizeStructure(ctx context.Context, in *CreatePrizeStructureRequest, opts ...grpc.CallOption) (*CreatePrizeStructureResponse, error)
	GetPrizeStructure(ctx context.Context, in *GetPrizeStructureRequest, opts ...grpc.CallOption) (*GetPrizeStructureResponse, error)
	UpdatePrizeStructure(ctx context.Context, in *UpdatePrizeStructureRequest, opts ...grpc.CallOption) (*UpdatePrizeStructureResponse, error)
	// Game approval workflow
	SubmitForApproval(ctx context.Context, in *SubmitForApprovalRequest, opts ...grpc.CallOption) (*SubmitForApprovalResponse, error)
	ApproveGame(ctx context.Context, in *ApproveGameRequest, opts ...grpc.CallOption) (*ApproveGameResponse, error)
	RejectGame(ctx context.Context, in *RejectGameRequest, opts ...grpc.CallOption) (*RejectGameResponse, error)
	GetApprovalStatus(ctx context.Context, in *GetApprovalStatusRequest, opts ...grpc.CallOption) (*GetApprovalStatusResponse, error)
	GetPendingApprovals(ctx context.Context, in *GetPendingApprovalsRequest, opts ...grpc.CallOption) (*GetPendingApprovalsResponse, error)
	// Game scheduling
	ScheduleGame(ctx context.Context, in *ScheduleGameRequest, opts ...grpc.CallOption) (*ScheduleGameResponse, error)
	GetGameSchedule(ctx context.Context, in *GetGameScheduleRequest, opts ...grpc.CallOption) (*GetGameScheduleResponse, error)
	GetScheduleById(ctx context.Context, in *GetScheduleByIdRequest, opts ...grpc.CallOption) (*GetScheduleByIdResponse, error)
	UpdateScheduledGame(ctx context.Context, in *UpdateScheduledGameRequest, opts ...grpc.CallOption) (*UpdateScheduledGameResponse, error)
	// Weekly scheduling
	GenerateWeeklySchedule(ctx context.Context, in *GenerateWeeklyScheduleRequest, opts ...grpc.CallOption) (*GenerateWeeklyScheduleResponse, error)
	GetWeeklySchedule(ctx context.Context, in *GetWeeklyScheduleRequest, opts ...grpc.CallOption) (*GetWeeklyScheduleResponse, error)
	ClearWeeklySchedule(ctx context.Context, in *ClearWeeklyScheduleRequest, opts ...grpc.CallOption) (*ClearWeeklyScheduleResponse, error)
	// Logo management
	UpdateGameLogo(ctx context.Context, in *UpdateGameLogoRequest, opts ...grpc.CallOption) (*UpdateGameLogoResponse, error)
	DeleteGameLogo(ctx context.Context, in *DeleteGameLogoRequest, opts ...grpc.CallOption) (*DeleteGameLogoResponse, error)
}

type gameServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGameServiceClient(cc grpc.ClientConnInterface) GameServiceClient {
	return &gameServiceClient{cc}
}

func (c *gameServiceClient) CreateGame(ctx context.Context, in *CreateGameRequest, opts ...grpc.CallOption) (*CreateGameResponse, error) {
	out := new(CreateGameResponse)
	err := c.cc.Invoke(ctx, "/game.v1.GameService/CreateGame", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameServiceClient) GetGame(ctx context.Context, in *GetGameRequest, opts ...grpc.CallOption) (*GetGameResponse, error) {
	out := new(GetGameResponse)
	err := c.cc.Invoke(ctx, "/game.v1.GameService/GetGame", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameServiceClient) UpdateGame(ctx context.Context, in *UpdateGameRequest, opts ...grpc.CallOption) (*UpdateGameResponse, error) {
	out := new(UpdateGameResponse)
	err := c.cc.Invoke(ctx, "/game.v1.GameService/UpdateGame", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameServiceClient) ListGames(ctx context.Context, in *ListGamesRequest, opts ...grpc.CallOption) (*ListGamesResponse, error) {
	out := new(ListGamesResponse)
	err := c.cc.Invoke(ctx, "/game.v1.GameService/ListGames", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameServiceClient) DeleteGame(ctx context.Context, in *DeleteGameRequest, opts ...grpc.CallOption) (*DeleteGameResponse, error) {
	out := new(DeleteGameResponse)
	err := c.cc.Invoke(ctx, "/game.v1.GameService/DeleteGame", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameServiceClient) ActivateGame(ctx context.Context, in *ActivateGameRequest, opts ...grpc.CallOption) (*ActivateGameResponse, error) {
	out := new(ActivateGameResponse)
	err := c.cc.Invoke(ctx, "/game.v1.GameService/ActivateGame", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameServiceClient) SuspendGame(ctx context.Context, in *SuspendGameRequest, opts ...grpc.CallOption) (*SuspendGameResponse, error) {
	out := new(SuspendGameResponse)
	err := c.cc.Invoke(ctx, "/game.v1.GameService/SuspendGame", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameServiceClient) CreateGameRules(ctx context.Context, in *CreateGameRulesRequest, opts ...grpc.CallOption) (*CreateGameRulesResponse, error) {
	out := new(CreateGameRulesResponse)
	err := c.cc.Invoke(ctx, "/game.v1.GameService/CreateGameRules", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameServiceClient) GetGameRules(ctx context.Context, in *GetGameRulesRequest, opts ...grpc.CallOption) (*GetGameRulesResponse, error) {
	out := new(GetGameRulesResponse)
	err := c.cc.Invoke(ctx, "/game.v1.GameService/GetGameRules", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameServiceClient) UpdateGameRules(ctx context.Context, in *UpdateGameRulesRequest, opts ...grpc.CallOption) (*UpdateGameRulesResponse, error) {
	out := new(UpdateGameRulesResponse)
	err := c.cc.Invoke(ctx, "/game.v1.GameService/UpdateGameRules", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameServiceClient) CreatePrizeStructure(ctx context.Context, in *CreatePrizeStructureRequest, opts ...grpc.CallOption) (*CreatePrizeStructureResponse, error) {
	out := new(CreatePrizeStructureResponse)
	err := c.cc.Invoke(ctx, "/game.v1.GameService/CreatePrizeStructure", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameServiceClient) GetPrizeStructure(ctx context.Context, in *GetPrizeStructureRequest, opts ...grpc.CallOption) (*GetPrizeStructureResponse, error) {
	out := new(GetPrizeStructureResponse)
	err := c.cc.Invoke(ctx, "/game.v1.GameService/GetPrizeStructure", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameServiceClient) UpdatePrizeStructure(ctx context.Context, in *UpdatePrizeStructureRequest, opts ...grpc.CallOption) (*UpdatePrizeStructureResponse, error) {
	out := new(UpdatePrizeStructureResponse)
	err := c.cc.Invoke(ctx, "/game.v1.GameService/UpdatePrizeStructure", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameServiceClient) SubmitForApproval(ctx context.Context, in *SubmitForApprovalRequest, opts ...grpc.CallOption) (*SubmitForApprovalResponse, error) {
	out := new(SubmitForApprovalResponse)
	err := c.cc.Invoke(ctx, "/game.v1.GameService/SubmitForApproval", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameServiceClient) ApproveGame(ctx context.Context, in *ApproveGameRequest, opts ...grpc.CallOption) (*ApproveGameResponse, error) {
	out := new(ApproveGameResponse)
	err := c.cc.Invoke(ctx, "/game.v1.GameService/ApproveGame", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameServiceClient) RejectGame(ctx context.Context, in *RejectGameRequest, opts ...grpc.CallOption) (*RejectGameResponse, error) {
	out := new(RejectGameResponse)
	err := c.cc.Invoke(ctx, "/game.v1.GameService/RejectGame", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameServiceClient) GetApprovalStatus(ctx context.Context, in *GetApprovalStatusRequest, opts ...grpc.CallOption) (*GetApprovalStatusResponse, error) {
	out := new(GetApprovalStatusResponse)
	err := c.cc.Invoke(ctx, "/game.v1.GameService/GetApprovalStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameServiceClient) GetPendingApprovals(ctx context.Context, in *GetPendingApprovalsRequest, opts ...grpc.CallOption) (*GetPendingApprovalsResponse, error) {
	out := new(GetPendingApprovalsResponse)
	err := c.cc.Invoke(ctx, "/game.v1.GameService/GetPendingApprovals", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameServiceClient) ScheduleGame(ctx context.Context, in *ScheduleGameRequest, opts ...grpc.CallOption) (*ScheduleGameResponse, error) {
	out := new(ScheduleGameResponse)
	err := c.cc.Invoke(ctx, "/game.v1.GameService/ScheduleGame", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameServiceClient) GetGameSchedule(ctx context.Context, in *GetGameScheduleRequest, opts ...grpc.CallOption) (*GetGameScheduleResponse, error) {
	out := new(GetGameScheduleResponse)
	err := c.cc.Invoke(ctx, "/game.v1.GameService/GetGameSchedule", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameServiceClient) GetScheduleById(ctx context.Context, in *GetScheduleByIdRequest, opts ...grpc.CallOption) (*GetScheduleByIdResponse, error) {
	out := new(GetScheduleByIdResponse)
	err := c.cc.Invoke(ctx, "/game.v1.GameService/GetScheduleById", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameServiceClient) UpdateScheduledGame(ctx context.Context, in *UpdateScheduledGameRequest, opts ...grpc.CallOption) (*UpdateScheduledGameResponse, error) {
	out := new(UpdateScheduledGameResponse)
	err := c.cc.Invoke(ctx, "/game.v1.GameService/UpdateScheduledGame", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameServiceClient) GenerateWeeklySchedule(ctx context.Context, in *GenerateWeeklyScheduleRequest, opts ...grpc.CallOption) (*GenerateWeeklyScheduleResponse, error) {
	out := new(GenerateWeeklyScheduleResponse)
	err := c.cc.Invoke(ctx, "/game.v1.GameService/GenerateWeeklySchedule", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameServiceClient) GetWeeklySchedule(ctx context.Context, in *GetWeeklyScheduleRequest, opts ...grpc.CallOption) (*GetWeeklyScheduleResponse, error) {
	out := new(GetWeeklyScheduleResponse)
	err := c.cc.Invoke(ctx, "/game.v1.GameService/GetWeeklySchedule", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameServiceClient) ClearWeeklySchedule(ctx context.Context, in *ClearWeeklyScheduleRequest, opts ...grpc.CallOption) (*ClearWeeklyScheduleResponse, error) {
	out := new(ClearWeeklyScheduleResponse)
	err := c.cc.Invoke(ctx, "/game.v1.GameService/ClearWeeklySchedule", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameServiceClient) UpdateGameLogo(ctx context.Context, in *UpdateGameLogoRequest, opts ...grpc.CallOption) (*UpdateGameLogoResponse, error) {
	out := new(UpdateGameLogoResponse)
	err := c.cc.Invoke(ctx, "/game.v1.GameService/UpdateGameLogo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameServiceClient) DeleteGameLogo(ctx context.Context, in *DeleteGameLogoRequest, opts ...grpc.CallOption) (*DeleteGameLogoResponse, error) {
	out := new(DeleteGameLogoResponse)
	err := c.cc.Invoke(ctx, "/game.v1.GameService/DeleteGameLogo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GameServiceServer is the server API for GameService service.
// All implementations should embed UnimplementedGameServiceServer
// for forward compatibility
type GameServiceServer interface {
	// Game management
	CreateGame(context.Context, *CreateGameRequest) (*CreateGameResponse, error)
	GetGame(context.Context, *GetGameRequest) (*GetGameResponse, error)
	UpdateGame(context.Context, *UpdateGameRequest) (*UpdateGameResponse, error)
	ListGames(context.Context, *ListGamesRequest) (*ListGamesResponse, error)
	DeleteGame(context.Context, *DeleteGameRequest) (*DeleteGameResponse, error)
	ActivateGame(context.Context, *ActivateGameRequest) (*ActivateGameResponse, error)
	SuspendGame(context.Context, *SuspendGameRequest) (*SuspendGameResponse, error)
	// Game rules management
	CreateGameRules(context.Context, *CreateGameRulesRequest) (*CreateGameRulesResponse, error)
	GetGameRules(context.Context, *GetGameRulesRequest) (*GetGameRulesResponse, error)
	UpdateGameRules(context.Context, *UpdateGameRulesRequest) (*UpdateGameRulesResponse, error)
	// Prize structure management
	CreatePrizeStructure(context.Context, *CreatePrizeStructureRequest) (*CreatePrizeStructureResponse, error)
	GetPrizeStructure(context.Context, *GetPrizeStructureRequest) (*GetPrizeStructureResponse, error)
	UpdatePrizeStructure(context.Context, *UpdatePrizeStructureRequest) (*UpdatePrizeStructureResponse, error)
	// Game approval workflow
	SubmitForApproval(context.Context, *SubmitForApprovalRequest) (*SubmitForApprovalResponse, error)
	ApproveGame(context.Context, *ApproveGameRequest) (*ApproveGameResponse, error)
	RejectGame(context.Context, *RejectGameRequest) (*RejectGameResponse, error)
	GetApprovalStatus(context.Context, *GetApprovalStatusRequest) (*GetApprovalStatusResponse, error)
	GetPendingApprovals(context.Context, *GetPendingApprovalsRequest) (*GetPendingApprovalsResponse, error)
	// Game scheduling
	ScheduleGame(context.Context, *ScheduleGameRequest) (*ScheduleGameResponse, error)
	GetGameSchedule(context.Context, *GetGameScheduleRequest) (*GetGameScheduleResponse, error)
	GetScheduleById(context.Context, *GetScheduleByIdRequest) (*GetScheduleByIdResponse, error)
	UpdateScheduledGame(context.Context, *UpdateScheduledGameRequest) (*UpdateScheduledGameResponse, error)
	// Weekly scheduling
	GenerateWeeklySchedule(context.Context, *GenerateWeeklyScheduleRequest) (*GenerateWeeklyScheduleResponse, error)
	GetWeeklySchedule(context.Context, *GetWeeklyScheduleRequest) (*GetWeeklyScheduleResponse, error)
	ClearWeeklySchedule(context.Context, *ClearWeeklyScheduleRequest) (*ClearWeeklyScheduleResponse, error)
	// Logo management
	UpdateGameLogo(context.Context, *UpdateGameLogoRequest) (*UpdateGameLogoResponse, error)
	DeleteGameLogo(context.Context, *DeleteGameLogoRequest) (*DeleteGameLogoResponse, error)
}

// UnimplementedGameServiceServer should be embedded to have forward compatible implementations.
type UnimplementedGameServiceServer struct {
}

func (UnimplementedGameServiceServer) CreateGame(context.Context, *CreateGameRequest) (*CreateGameResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateGame not implemented")
}
func (UnimplementedGameServiceServer) GetGame(context.Context, *GetGameRequest) (*GetGameResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetGame not implemented")
}
func (UnimplementedGameServiceServer) UpdateGame(context.Context, *UpdateGameRequest) (*UpdateGameResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateGame not implemented")
}
func (UnimplementedGameServiceServer) ListGames(context.Context, *ListGamesRequest) (*ListGamesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListGames not implemented")
}
func (UnimplementedGameServiceServer) DeleteGame(context.Context, *DeleteGameRequest) (*DeleteGameResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteGame not implemented")
}
func (UnimplementedGameServiceServer) ActivateGame(context.Context, *ActivateGameRequest) (*ActivateGameResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ActivateGame not implemented")
}
func (UnimplementedGameServiceServer) SuspendGame(context.Context, *SuspendGameRequest) (*SuspendGameResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SuspendGame not implemented")
}
func (UnimplementedGameServiceServer) CreateGameRules(context.Context, *CreateGameRulesRequest) (*CreateGameRulesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateGameRules not implemented")
}
func (UnimplementedGameServiceServer) GetGameRules(context.Context, *GetGameRulesRequest) (*GetGameRulesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetGameRules not implemented")
}
func (UnimplementedGameServiceServer) UpdateGameRules(context.Context, *UpdateGameRulesRequest) (*UpdateGameRulesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateGameRules not implemented")
}
func (UnimplementedGameServiceServer) CreatePrizeStructure(context.Context, *CreatePrizeStructureRequest) (*CreatePrizeStructureResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreatePrizeStructure not implemented")
}
func (UnimplementedGameServiceServer) GetPrizeStructure(context.Context, *GetPrizeStructureRequest) (*GetPrizeStructureResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPrizeStructure not implemented")
}
func (UnimplementedGameServiceServer) UpdatePrizeStructure(context.Context, *UpdatePrizeStructureRequest) (*UpdatePrizeStructureResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdatePrizeStructure not implemented")
}
func (UnimplementedGameServiceServer) SubmitForApproval(context.Context, *SubmitForApprovalRequest) (*SubmitForApprovalResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubmitForApproval not implemented")
}
func (UnimplementedGameServiceServer) ApproveGame(context.Context, *ApproveGameRequest) (*ApproveGameResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ApproveGame not implemented")
}
func (UnimplementedGameServiceServer) RejectGame(context.Context, *RejectGameRequest) (*RejectGameResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RejectGame not implemented")
}
func (UnimplementedGameServiceServer) GetApprovalStatus(context.Context, *GetApprovalStatusRequest) (*GetApprovalStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetApprovalStatus not implemented")
}
func (UnimplementedGameServiceServer) GetPendingApprovals(context.Context, *GetPendingApprovalsRequest) (*GetPendingApprovalsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPendingApprovals not implemented")
}
func (UnimplementedGameServiceServer) ScheduleGame(context.Context, *ScheduleGameRequest) (*ScheduleGameResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ScheduleGame not implemented")
}
func (UnimplementedGameServiceServer) GetGameSchedule(context.Context, *GetGameScheduleRequest) (*GetGameScheduleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetGameSchedule not implemented")
}
func (UnimplementedGameServiceServer) GetScheduleById(context.Context, *GetScheduleByIdRequest) (*GetScheduleByIdResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetScheduleById not implemented")
}
func (UnimplementedGameServiceServer) UpdateScheduledGame(context.Context, *UpdateScheduledGameRequest) (*UpdateScheduledGameResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateScheduledGame not implemented")
}
func (UnimplementedGameServiceServer) GenerateWeeklySchedule(context.Context, *GenerateWeeklyScheduleRequest) (*GenerateWeeklyScheduleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GenerateWeeklySchedule not implemented")
}
func (UnimplementedGameServiceServer) GetWeeklySchedule(context.Context, *GetWeeklyScheduleRequest) (*GetWeeklyScheduleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetWeeklySchedule not implemented")
}
func (UnimplementedGameServiceServer) ClearWeeklySchedule(context.Context, *ClearWeeklyScheduleRequest) (*ClearWeeklyScheduleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ClearWeeklySchedule not implemented")
}
func (UnimplementedGameServiceServer) UpdateGameLogo(context.Context, *UpdateGameLogoRequest) (*UpdateGameLogoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateGameLogo not implemented")
}
func (UnimplementedGameServiceServer) DeleteGameLogo(context.Context, *DeleteGameLogoRequest) (*DeleteGameLogoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteGameLogo not implemented")
}

// UnsafeGameServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GameServiceServer will
// result in compilation errors.
type UnsafeGameServiceServer interface {
	mustEmbedUnimplementedGameServiceServer()
}

func RegisterGameServiceServer(s grpc.ServiceRegistrar, srv GameServiceServer) {
	s.RegisterService(&GameService_ServiceDesc, srv)
}

func _GameService_CreateGame_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateGameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameServiceServer).CreateGame(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/game.v1.GameService/CreateGame",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameServiceServer).CreateGame(ctx, req.(*CreateGameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GameService_GetGame_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameServiceServer).GetGame(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/game.v1.GameService/GetGame",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameServiceServer).GetGame(ctx, req.(*GetGameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GameService_UpdateGame_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateGameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameServiceServer).UpdateGame(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/game.v1.GameService/UpdateGame",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameServiceServer).UpdateGame(ctx, req.(*UpdateGameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GameService_ListGames_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListGamesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameServiceServer).ListGames(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/game.v1.GameService/ListGames",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameServiceServer).ListGames(ctx, req.(*ListGamesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GameService_DeleteGame_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteGameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameServiceServer).DeleteGame(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/game.v1.GameService/DeleteGame",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameServiceServer).DeleteGame(ctx, req.(*DeleteGameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GameService_ActivateGame_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ActivateGameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameServiceServer).ActivateGame(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/game.v1.GameService/ActivateGame",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameServiceServer).ActivateGame(ctx, req.(*ActivateGameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GameService_SuspendGame_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SuspendGameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameServiceServer).SuspendGame(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/game.v1.GameService/SuspendGame",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameServiceServer).SuspendGame(ctx, req.(*SuspendGameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GameService_CreateGameRules_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateGameRulesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameServiceServer).CreateGameRules(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/game.v1.GameService/CreateGameRules",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameServiceServer).CreateGameRules(ctx, req.(*CreateGameRulesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GameService_GetGameRules_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGameRulesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameServiceServer).GetGameRules(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/game.v1.GameService/GetGameRules",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameServiceServer).GetGameRules(ctx, req.(*GetGameRulesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GameService_UpdateGameRules_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateGameRulesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameServiceServer).UpdateGameRules(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/game.v1.GameService/UpdateGameRules",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameServiceServer).UpdateGameRules(ctx, req.(*UpdateGameRulesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GameService_CreatePrizeStructure_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePrizeStructureRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameServiceServer).CreatePrizeStructure(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/game.v1.GameService/CreatePrizeStructure",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameServiceServer).CreatePrizeStructure(ctx, req.(*CreatePrizeStructureRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GameService_GetPrizeStructure_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPrizeStructureRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameServiceServer).GetPrizeStructure(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/game.v1.GameService/GetPrizeStructure",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameServiceServer).GetPrizeStructure(ctx, req.(*GetPrizeStructureRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GameService_UpdatePrizeStructure_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdatePrizeStructureRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameServiceServer).UpdatePrizeStructure(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/game.v1.GameService/UpdatePrizeStructure",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameServiceServer).UpdatePrizeStructure(ctx, req.(*UpdatePrizeStructureRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GameService_SubmitForApproval_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitForApprovalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameServiceServer).SubmitForApproval(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/game.v1.GameService/SubmitForApproval",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameServiceServer).SubmitForApproval(ctx, req.(*SubmitForApprovalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GameService_ApproveGame_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApproveGameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameServiceServer).ApproveGame(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/game.v1.GameService/ApproveGame",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameServiceServer).ApproveGame(ctx, req.(*ApproveGameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GameService_RejectGame_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RejectGameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameServiceServer).RejectGame(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/game.v1.GameService/RejectGame",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameServiceServer).RejectGame(ctx, req.(*RejectGameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GameService_GetApprovalStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetApprovalStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameServiceServer).GetApprovalStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/game.v1.GameService/GetApprovalStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameServiceServer).GetApprovalStatus(ctx, req.(*GetApprovalStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GameService_GetPendingApprovals_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPendingApprovalsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameServiceServer).GetPendingApprovals(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/game.v1.GameService/GetPendingApprovals",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameServiceServer).GetPendingApprovals(ctx, req.(*GetPendingApprovalsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GameService_ScheduleGame_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ScheduleGameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameServiceServer).ScheduleGame(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/game.v1.GameService/ScheduleGame",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameServiceServer).ScheduleGame(ctx, req.(*ScheduleGameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GameService_GetGameSchedule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGameScheduleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameServiceServer).GetGameSchedule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/game.v1.GameService/GetGameSchedule",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameServiceServer).GetGameSchedule(ctx, req.(*GetGameScheduleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GameService_GetScheduleById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetScheduleByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameServiceServer).GetScheduleById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/game.v1.GameService/GetScheduleById",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameServiceServer).GetScheduleById(ctx, req.(*GetScheduleByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GameService_UpdateScheduledGame_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateScheduledGameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameServiceServer).UpdateScheduledGame(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/game.v1.GameService/UpdateScheduledGame",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameServiceServer).UpdateScheduledGame(ctx, req.(*UpdateScheduledGameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GameService_GenerateWeeklySchedule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateWeeklyScheduleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameServiceServer).GenerateWeeklySchedule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/game.v1.GameService/GenerateWeeklySchedule",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameServiceServer).GenerateWeeklySchedule(ctx, req.(*GenerateWeeklyScheduleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GameService_GetWeeklySchedule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWeeklyScheduleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameServiceServer).GetWeeklySchedule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/game.v1.GameService/GetWeeklySchedule",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameServiceServer).GetWeeklySchedule(ctx, req.(*GetWeeklyScheduleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GameService_ClearWeeklySchedule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClearWeeklyScheduleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameServiceServer).ClearWeeklySchedule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/game.v1.GameService/ClearWeeklySchedule",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameServiceServer).ClearWeeklySchedule(ctx, req.(*ClearWeeklyScheduleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GameService_UpdateGameLogo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateGameLogoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameServiceServer).UpdateGameLogo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/game.v1.GameService/UpdateGameLogo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameServiceServer).UpdateGameLogo(ctx, req.(*UpdateGameLogoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GameService_DeleteGameLogo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteGameLogoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameServiceServer).DeleteGameLogo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/game.v1.GameService/DeleteGameLogo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameServiceServer).DeleteGameLogo(ctx, req.(*DeleteGameLogoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GameService_ServiceDesc is the grpc.ServiceDesc for GameService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GameService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "game.v1.GameService",
	HandlerType: (*GameServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateGame",
			Handler:    _GameService_CreateGame_Handler,
		},
		{
			MethodName: "GetGame",
			Handler:    _GameService_GetGame_Handler,
		},
		{
			MethodName: "UpdateGame",
			Handler:    _GameService_UpdateGame_Handler,
		},
		{
			MethodName: "ListGames",
			Handler:    _GameService_ListGames_Handler,
		},
		{
			MethodName: "DeleteGame",
			Handler:    _GameService_DeleteGame_Handler,
		},
		{
			MethodName: "ActivateGame",
			Handler:    _GameService_ActivateGame_Handler,
		},
		{
			MethodName: "SuspendGame",
			Handler:    _GameService_SuspendGame_Handler,
		},
		{
			MethodName: "CreateGameRules",
			Handler:    _GameService_CreateGameRules_Handler,
		},
		{
			MethodName: "GetGameRules",
			Handler:    _GameService_GetGameRules_Handler,
		},
		{
			MethodName: "UpdateGameRules",
			Handler:    _GameService_UpdateGameRules_Handler,
		},
		{
			MethodName: "CreatePrizeStructure",
			Handler:    _GameService_CreatePrizeStructure_Handler,
		},
		{
			MethodName: "GetPrizeStructure",
			Handler:    _GameService_GetPrizeStructure_Handler,
		},
		{
			MethodName: "UpdatePrizeStructure",
			Handler:    _GameService_UpdatePrizeStructure_Handler,
		},
		{
			MethodName: "SubmitForApproval",
			Handler:    _GameService_SubmitForApproval_Handler,
		},
		{
			MethodName: "ApproveGame",
			Handler:    _GameService_ApproveGame_Handler,
		},
		{
			MethodName: "RejectGame",
			Handler:    _GameService_RejectGame_Handler,
		},
		{
			MethodName: "GetApprovalStatus",
			Handler:    _GameService_GetApprovalStatus_Handler,
		},
		{
			MethodName: "GetPendingApprovals",
			Handler:    _GameService_GetPendingApprovals_Handler,
		},
		{
			MethodName: "ScheduleGame",
			Handler:    _GameService_ScheduleGame_Handler,
		},
		{
			MethodName: "GetGameSchedule",
			Handler:    _GameService_GetGameSchedule_Handler,
		},
		{
			MethodName: "GetScheduleById",
			Handler:    _GameService_GetScheduleById_Handler,
		},
		{
			MethodName: "UpdateScheduledGame",
			Handler:    _GameService_UpdateScheduledGame_Handler,
		},
		{
			MethodName: "GenerateWeeklySchedule",
			Handler:    _GameService_GenerateWeeklySchedule_Handler,
		},
		{
			MethodName: "GetWeeklySchedule",
			Handler:    _GameService_GetWeeklySchedule_Handler,
		},
		{
			MethodName: "ClearWeeklySchedule",
			Handler:    _GameService_ClearWeeklySchedule_Handler,
		},
		{
			MethodName: "UpdateGameLogo",
			Handler:    _GameService_UpdateGameLogo_Handler,
		},
		{
			MethodName: "DeleteGameLogo",
			Handler:    _GameService_DeleteGameLogo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/game/v1/game.proto",
}
