// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v5.28.3
// source: proto/game/v1/game.proto

package gamev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GameService_CreateGame_FullMethodName             = "/game.v1.GameService/CreateGame"
	GameService_GetGame_FullMethodName                = "/game.v1.GameService/GetGame"
	GameService_UpdateGame_FullMethodName             = "/game.v1.GameService/UpdateGame"
	GameService_ListGames_FullMethodName              = "/game.v1.GameService/ListGames"
	GameService_DeleteGame_FullMethodName             = "/game.v1.GameService/DeleteGame"
	GameService_ActivateGame_FullMethodName           = "/game.v1.GameService/ActivateGame"
	GameService_SuspendGame_FullMethodName            = "/game.v1.GameService/SuspendGame"
	GameService_CreateGameRules_FullMethodName        = "/game.v1.GameService/CreateGameRules"
	GameService_GetGameRules_FullMethodName           = "/game.v1.GameService/GetGameRules"
	GameService_UpdateGameRules_FullMethodName        = "/game.v1.GameService/UpdateGameRules"
	GameService_CreatePrizeStructure_FullMethodName   = "/game.v1.GameService/CreatePrizeStructure"
	GameService_GetPrizeStructure_FullMethodName      = "/game.v1.GameService/GetPrizeStructure"
	GameService_UpdatePrizeStructure_FullMethodName   = "/game.v1.GameService/UpdatePrizeStructure"
	GameService_SubmitForApproval_FullMethodName      = "/game.v1.GameService/SubmitForApproval"
	GameService_ApproveGame_FullMethodName            = "/game.v1.GameService/ApproveGame"
	GameService_RejectGame_FullMethodName             = "/game.v1.GameService/RejectGame"
	GameService_GetApprovalStatus_FullMethodName      = "/game.v1.GameService/GetApprovalStatus"
	GameService_GetPendingApprovals_FullMethodName    = "/game.v1.GameService/GetPendingApprovals"
	GameService_ScheduleGame_FullMethodName           = "/game.v1.GameService/ScheduleGame"
	GameService_GetGameSchedule_FullMethodName        = "/game.v1.GameService/GetGameSchedule"
	GameService_GetScheduleById_FullMethodName        = "/game.v1.GameService/GetScheduleById"
	GameService_UpdateScheduledGame_FullMethodName    = "/game.v1.GameService/UpdateScheduledGame"
	GameService_GenerateWeeklySchedule_FullMethodName = "/game.v1.GameService/GenerateWeeklySchedule"
	GameService_GetWeeklySchedule_FullMethodName      = "/game.v1.GameService/GetWeeklySchedule"
	GameService_ClearWeeklySchedule_FullMethodName    = "/game.v1.GameService/ClearWeeklySchedule"
	GameService_UpdateGameLogo_FullMethodName         = "/game.v1.GameService/UpdateGameLogo"
	GameService_DeleteGameLogo_FullMethodName         = "/game.v1.GameService/DeleteGameLogo"
)

// GameServiceClient is the client API for GameService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GameServiceClient interface {
	// Game management
	CreateGame(ctx context.Context, in *CreateGameRequest, opts ...grpc.CallOption) (*CreateGameResponse, error)
	GetGame(ctx context.Context, in *GetGameRequest, opts ...grpc.CallOption) (*GetGameResponse, error)
	UpdateGame(ctx context.Context, in *UpdateGameRequest, opts ...grpc.CallOption) (*UpdateGameResponse, error)
	ListGames(ctx context.Context, in *ListGamesRequest, opts ...grpc.CallOption) (*ListGamesResponse, error)
	DeleteGame(ctx context.Context, in *DeleteGameRequest, opts ...grpc.CallOption) (*DeleteGameResponse, error)
	ActivateGame(ctx context.Context, in *ActivateGameRequest, opts ...grpc.CallOption) (*ActivateGameResponse, error)
	SuspendGame(ctx context.Context, in *SuspendGameRequest, opts ...grpc.CallOption) (*SuspendGameResponse, error)
	// Game rules management
	CreateGameRules(ctx context.Context, in *CreateGameRulesRequest, opts ...grpc.CallOption) (*CreateGameRulesResponse, error)
	GetGameRules(ctx context.Context, in *GetGameRulesRequest, opts ...grpc.CallOption) (*GetGameRulesResponse, error)
	UpdateGameRules(ctx context.Context, in *UpdateGameRulesRequest, opts ...grpc.CallOption) (*UpdateGameRulesResponse, error)
	// Prize structure management
	CreatePrizeStructure(ctx context.Context, in *CreatePrizeStructureRequest, opts ...grpc.CallOption) (*CreatePrizeStructureResponse, error)
	GetPrizeStructure(ctx context.Context, in *GetPrizeStructureRequest, opts ...grpc.CallOption) (*GetPrizeStructureResponse, error)
	UpdatePrizeStructure(ctx context.Context, in *UpdatePrizeStructureRequest, opts ...grpc.CallOption) (*UpdatePrizeStructureResponse, error)
	// Game approval workflow
	SubmitForApproval(ctx context.Context, in *SubmitForApprovalRequest, opts ...grpc.CallOption) (*SubmitForApprovalResponse, error)
	ApproveGame(ctx context.Context, in *ApproveGameRequest, opts ...grpc.CallOption) (*ApproveGameResponse, error)
	RejectGame(ctx context.Context, in *RejectGameRequest, opts ...grpc.CallOption) (*RejectGameResponse, error)
	GetApprovalStatus(ctx context.Context, in *GetApprovalStatusRequest, opts ...grpc.CallOption) (*GetApprovalStatusResponse, error)
	GetPendingApprovals(ctx context.Context, in *GetPendingApprovalsRequest, opts ...grpc.CallOption) (*GetPendingApprovalsResponse, error)
	// Game scheduling
	ScheduleGame(ctx context.Context, in *ScheduleGameRequest, opts ...grpc.CallOption) (*ScheduleGameResponse, error)
	GetGameSchedule(ctx context.Context, in *GetGameScheduleRequest, opts ...grpc.CallOption) (*GetGameScheduleResponse, error)
	GetScheduleById(ctx context.Context, in *GetScheduleByIdRequest, opts ...grpc.CallOption) (*GetScheduleByIdResponse, error)
	UpdateScheduledGame(ctx context.Context, in *UpdateScheduledGameRequest, opts ...grpc.CallOption) (*UpdateScheduledGameResponse, error)
	// Weekly scheduling
	GenerateWeeklySchedule(ctx context.Context, in *GenerateWeeklyScheduleRequest, opts ...grpc.CallOption) (*GenerateWeeklyScheduleResponse, error)
	GetWeeklySchedule(ctx context.Context, in *GetWeeklyScheduleRequest, opts ...grpc.CallOption) (*GetWeeklyScheduleResponse, error)
	ClearWeeklySchedule(ctx context.Context, in *ClearWeeklyScheduleRequest, opts ...grpc.CallOption) (*ClearWeeklyScheduleResponse, error)
	// Logo management
	UpdateGameLogo(ctx context.Context, in *UpdateGameLogoRequest, opts ...grpc.CallOption) (*UpdateGameLogoResponse, error)
	DeleteGameLogo(ctx context.Context, in *DeleteGameLogoRequest, opts ...grpc.CallOption) (*DeleteGameLogoResponse, error)
}

type gameServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGameServiceClient(cc grpc.ClientConnInterface) GameServiceClient {
	return &gameServiceClient{cc}
}

func (c *gameServiceClient) CreateGame(ctx context.Context, in *CreateGameRequest, opts ...grpc.CallOption) (*CreateGameResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateGameResponse)
	err := c.cc.Invoke(ctx, GameService_CreateGame_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameServiceClient) GetGame(ctx context.Context, in *GetGameRequest, opts ...grpc.CallOption) (*GetGameResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetGameResponse)
	err := c.cc.Invoke(ctx, GameService_GetGame_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameServiceClient) UpdateGame(ctx context.Context, in *UpdateGameRequest, opts ...grpc.CallOption) (*UpdateGameResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateGameResponse)
	err := c.cc.Invoke(ctx, GameService_UpdateGame_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameServiceClient) ListGames(ctx context.Context, in *ListGamesRequest, opts ...grpc.CallOption) (*ListGamesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListGamesResponse)
	err := c.cc.Invoke(ctx, GameService_ListGames_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameServiceClient) DeleteGame(ctx context.Context, in *DeleteGameRequest, opts ...grpc.CallOption) (*DeleteGameResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteGameResponse)
	err := c.cc.Invoke(ctx, GameService_DeleteGame_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameServiceClient) ActivateGame(ctx context.Context, in *ActivateGameRequest, opts ...grpc.CallOption) (*ActivateGameResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ActivateGameResponse)
	err := c.cc.Invoke(ctx, GameService_ActivateGame_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameServiceClient) SuspendGame(ctx context.Context, in *SuspendGameRequest, opts ...grpc.CallOption) (*SuspendGameResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SuspendGameResponse)
	err := c.cc.Invoke(ctx, GameService_SuspendGame_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameServiceClient) CreateGameRules(ctx context.Context, in *CreateGameRulesRequest, opts ...grpc.CallOption) (*CreateGameRulesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateGameRulesResponse)
	err := c.cc.Invoke(ctx, GameService_CreateGameRules_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameServiceClient) GetGameRules(ctx context.Context, in *GetGameRulesRequest, opts ...grpc.CallOption) (*GetGameRulesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetGameRulesResponse)
	err := c.cc.Invoke(ctx, GameService_GetGameRules_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameServiceClient) UpdateGameRules(ctx context.Context, in *UpdateGameRulesRequest, opts ...grpc.CallOption) (*UpdateGameRulesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateGameRulesResponse)
	err := c.cc.Invoke(ctx, GameService_UpdateGameRules_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameServiceClient) CreatePrizeStructure(ctx context.Context, in *CreatePrizeStructureRequest, opts ...grpc.CallOption) (*CreatePrizeStructureResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreatePrizeStructureResponse)
	err := c.cc.Invoke(ctx, GameService_CreatePrizeStructure_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameServiceClient) GetPrizeStructure(ctx context.Context, in *GetPrizeStructureRequest, opts ...grpc.CallOption) (*GetPrizeStructureResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPrizeStructureResponse)
	err := c.cc.Invoke(ctx, GameService_GetPrizeStructure_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameServiceClient) UpdatePrizeStructure(ctx context.Context, in *UpdatePrizeStructureRequest, opts ...grpc.CallOption) (*UpdatePrizeStructureResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdatePrizeStructureResponse)
	err := c.cc.Invoke(ctx, GameService_UpdatePrizeStructure_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameServiceClient) SubmitForApproval(ctx context.Context, in *SubmitForApprovalRequest, opts ...grpc.CallOption) (*SubmitForApprovalResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubmitForApprovalResponse)
	err := c.cc.Invoke(ctx, GameService_SubmitForApproval_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameServiceClient) ApproveGame(ctx context.Context, in *ApproveGameRequest, opts ...grpc.CallOption) (*ApproveGameResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApproveGameResponse)
	err := c.cc.Invoke(ctx, GameService_ApproveGame_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameServiceClient) RejectGame(ctx context.Context, in *RejectGameRequest, opts ...grpc.CallOption) (*RejectGameResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RejectGameResponse)
	err := c.cc.Invoke(ctx, GameService_RejectGame_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameServiceClient) GetApprovalStatus(ctx context.Context, in *GetApprovalStatusRequest, opts ...grpc.CallOption) (*GetApprovalStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetApprovalStatusResponse)
	err := c.cc.Invoke(ctx, GameService_GetApprovalStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameServiceClient) GetPendingApprovals(ctx context.Context, in *GetPendingApprovalsRequest, opts ...grpc.CallOption) (*GetPendingApprovalsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPendingApprovalsResponse)
	err := c.cc.Invoke(ctx, GameService_GetPendingApprovals_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameServiceClient) ScheduleGame(ctx context.Context, in *ScheduleGameRequest, opts ...grpc.CallOption) (*ScheduleGameResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ScheduleGameResponse)
	err := c.cc.Invoke(ctx, GameService_ScheduleGame_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameServiceClient) GetGameSchedule(ctx context.Context, in *GetGameScheduleRequest, opts ...grpc.CallOption) (*GetGameScheduleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetGameScheduleResponse)
	err := c.cc.Invoke(ctx, GameService_GetGameSchedule_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameServiceClient) GetScheduleById(ctx context.Context, in *GetScheduleByIdRequest, opts ...grpc.CallOption) (*GetScheduleByIdResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetScheduleByIdResponse)
	err := c.cc.Invoke(ctx, GameService_GetScheduleById_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameServiceClient) UpdateScheduledGame(ctx context.Context, in *UpdateScheduledGameRequest, opts ...grpc.CallOption) (*UpdateScheduledGameResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateScheduledGameResponse)
	err := c.cc.Invoke(ctx, GameService_UpdateScheduledGame_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameServiceClient) GenerateWeeklySchedule(ctx context.Context, in *GenerateWeeklyScheduleRequest, opts ...grpc.CallOption) (*GenerateWeeklyScheduleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GenerateWeeklyScheduleResponse)
	err := c.cc.Invoke(ctx, GameService_GenerateWeeklySchedule_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameServiceClient) GetWeeklySchedule(ctx context.Context, in *GetWeeklyScheduleRequest, opts ...grpc.CallOption) (*GetWeeklyScheduleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetWeeklyScheduleResponse)
	err := c.cc.Invoke(ctx, GameService_GetWeeklySchedule_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameServiceClient) ClearWeeklySchedule(ctx context.Context, in *ClearWeeklyScheduleRequest, opts ...grpc.CallOption) (*ClearWeeklyScheduleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ClearWeeklyScheduleResponse)
	err := c.cc.Invoke(ctx, GameService_ClearWeeklySchedule_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameServiceClient) UpdateGameLogo(ctx context.Context, in *UpdateGameLogoRequest, opts ...grpc.CallOption) (*UpdateGameLogoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateGameLogoResponse)
	err := c.cc.Invoke(ctx, GameService_UpdateGameLogo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameServiceClient) DeleteGameLogo(ctx context.Context, in *DeleteGameLogoRequest, opts ...grpc.CallOption) (*DeleteGameLogoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteGameLogoResponse)
	err := c.cc.Invoke(ctx, GameService_DeleteGameLogo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GameServiceServer is the server API for GameService service.
// All implementations must embed UnimplementedGameServiceServer
// for forward compatibility.
type GameServiceServer interface {
	// Game management
	CreateGame(context.Context, *CreateGameRequest) (*CreateGameResponse, error)
	GetGame(context.Context, *GetGameRequest) (*GetGameResponse, error)
	UpdateGame(context.Context, *UpdateGameRequest) (*UpdateGameResponse, error)
	ListGames(context.Context, *ListGamesRequest) (*ListGamesResponse, error)
	DeleteGame(context.Context, *DeleteGameRequest) (*DeleteGameResponse, error)
	ActivateGame(context.Context, *ActivateGameRequest) (*ActivateGameResponse, error)
	SuspendGame(context.Context, *SuspendGameRequest) (*SuspendGameResponse, error)
	// Game rules management
	CreateGameRules(context.Context, *CreateGameRulesRequest) (*CreateGameRulesResponse, error)
	GetGameRules(context.Context, *GetGameRulesRequest) (*GetGameRulesResponse, error)
	UpdateGameRules(context.Context, *UpdateGameRulesRequest) (*UpdateGameRulesResponse, error)
	// Prize structure management
	CreatePrizeStructure(context.Context, *CreatePrizeStructureRequest) (*CreatePrizeStructureResponse, error)
	GetPrizeStructure(context.Context, *GetPrizeStructureRequest) (*GetPrizeStructureResponse, error)
	UpdatePrizeStructure(context.Context, *UpdatePrizeStructureRequest) (*UpdatePrizeStructureResponse, error)
	// Game approval workflow
	SubmitForApproval(context.Context, *SubmitForApprovalRequest) (*SubmitForApprovalResponse, error)
	ApproveGame(context.Context, *ApproveGameRequest) (*ApproveGameResponse, error)
	RejectGame(context.Context, *RejectGameRequest) (*RejectGameResponse, error)
	GetApprovalStatus(context.Context, *GetApprovalStatusRequest) (*GetApprovalStatusResponse, error)
	GetPendingApprovals(context.Context, *GetPendingApprovalsRequest) (*GetPendingApprovalsResponse, error)
	// Game scheduling
	ScheduleGame(context.Context, *ScheduleGameRequest) (*ScheduleGameResponse, error)
	GetGameSchedule(context.Context, *GetGameScheduleRequest) (*GetGameScheduleResponse, error)
	GetScheduleById(context.Context, *GetScheduleByIdRequest) (*GetScheduleByIdResponse, error)
	UpdateScheduledGame(context.Context, *UpdateScheduledGameRequest) (*UpdateScheduledGameResponse, error)
	// Weekly scheduling
	GenerateWeeklySchedule(context.Context, *GenerateWeeklyScheduleRequest) (*GenerateWeeklyScheduleResponse, error)
	GetWeeklySchedule(context.Context, *GetWeeklyScheduleRequest) (*GetWeeklyScheduleResponse, error)
	ClearWeeklySchedule(context.Context, *ClearWeeklyScheduleRequest) (*ClearWeeklyScheduleResponse, error)
	// Logo management
	UpdateGameLogo(context.Context, *UpdateGameLogoRequest) (*UpdateGameLogoResponse, error)
	DeleteGameLogo(context.Context, *DeleteGameLogoRequest) (*DeleteGameLogoResponse, error)
	mustEmbedUnimplementedGameServiceServer()
}

// UnimplementedGameServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGameServiceServer struct{}

func (UnimplementedGameServiceServer) CreateGame(context.Context, *CreateGameRequest) (*CreateGameResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateGame not implemented")
}
func (UnimplementedGameServiceServer) GetGame(context.Context, *GetGameRequest) (*GetGameResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetGame not implemented")
}
func (UnimplementedGameServiceServer) UpdateGame(context.Context, *UpdateGameRequest) (*UpdateGameResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateGame not implemented")
}
func (UnimplementedGameServiceServer) ListGames(context.Context, *ListGamesRequest) (*ListGamesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListGames not implemented")
}
func (UnimplementedGameServiceServer) DeleteGame(context.Context, *DeleteGameRequest) (*DeleteGameResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteGame not implemented")
}
func (UnimplementedGameServiceServer) ActivateGame(context.Context, *ActivateGameRequest) (*ActivateGameResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ActivateGame not implemented")
}
func (UnimplementedGameServiceServer) SuspendGame(context.Context, *SuspendGameRequest) (*SuspendGameResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SuspendGame not implemented")
}
func (UnimplementedGameServiceServer) CreateGameRules(context.Context, *CreateGameRulesRequest) (*CreateGameRulesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateGameRules not implemented")
}
func (UnimplementedGameServiceServer) GetGameRules(context.Context, *GetGameRulesRequest) (*GetGameRulesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetGameRules not implemented")
}
func (UnimplementedGameServiceServer) UpdateGameRules(context.Context, *UpdateGameRulesRequest) (*UpdateGameRulesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateGameRules not implemented")
}
func (UnimplementedGameServiceServer) CreatePrizeStructure(context.Context, *CreatePrizeStructureRequest) (*CreatePrizeStructureResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreatePrizeStructure not implemented")
}
func (UnimplementedGameServiceServer) GetPrizeStructure(context.Context, *GetPrizeStructureRequest) (*GetPrizeStructureResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPrizeStructure not implemented")
}
func (UnimplementedGameServiceServer) UpdatePrizeStructure(context.Context, *UpdatePrizeStructureRequest) (*UpdatePrizeStructureResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdatePrizeStructure not implemented")
}
func (UnimplementedGameServiceServer) SubmitForApproval(context.Context, *SubmitForApprovalRequest) (*SubmitForApprovalResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SubmitForApproval not implemented")
}
func (UnimplementedGameServiceServer) ApproveGame(context.Context, *ApproveGameRequest) (*ApproveGameResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ApproveGame not implemented")
}
func (UnimplementedGameServiceServer) RejectGame(context.Context, *RejectGameRequest) (*RejectGameResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RejectGame not implemented")
}
func (UnimplementedGameServiceServer) GetApprovalStatus(context.Context, *GetApprovalStatusRequest) (*GetApprovalStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetApprovalStatus not implemented")
}
func (UnimplementedGameServiceServer) GetPendingApprovals(context.Context, *GetPendingApprovalsRequest) (*GetPendingApprovalsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPendingApprovals not implemented")
}
func (UnimplementedGameServiceServer) ScheduleGame(context.Context, *ScheduleGameRequest) (*ScheduleGameResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ScheduleGame not implemented")
}
func (UnimplementedGameServiceServer) GetGameSchedule(context.Context, *GetGameScheduleRequest) (*GetGameScheduleResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetGameSchedule not implemented")
}
func (UnimplementedGameServiceServer) GetScheduleById(context.Context, *GetScheduleByIdRequest) (*GetScheduleByIdResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetScheduleById not implemented")
}
func (UnimplementedGameServiceServer) UpdateScheduledGame(context.Context, *UpdateScheduledGameRequest) (*UpdateScheduledGameResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateScheduledGame not implemented")
}
func (UnimplementedGameServiceServer) GenerateWeeklySchedule(context.Context, *GenerateWeeklyScheduleRequest) (*GenerateWeeklyScheduleResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GenerateWeeklySchedule not implemented")
}
func (UnimplementedGameServiceServer) GetWeeklySchedule(context.Context, *GetWeeklyScheduleRequest) (*GetWeeklyScheduleResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetWeeklySchedule not implemented")
}
func (UnimplementedGameServiceServer) ClearWeeklySchedule(context.Context, *ClearWeeklyScheduleRequest) (*ClearWeeklyScheduleResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ClearWeeklySchedule not implemented")
}
func (UnimplementedGameServiceServer) UpdateGameLogo(context.Context, *UpdateGameLogoRequest) (*UpdateGameLogoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateGameLogo not implemented")
}
func (UnimplementedGameServiceServer) DeleteGameLogo(context.Context, *DeleteGameLogoRequest) (*DeleteGameLogoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteGameLogo not implemented")
}
func (UnimplementedGameServiceServer) mustEmbedUnimplementedGameServiceServer() {}
func (UnimplementedGameServiceServer) testEmbeddedByValue()                     {}

// UnsafeGameServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GameServiceServer will
// result in compilation errors.
type UnsafeGameServiceServer interface {
	mustEmbedUnimplementedGameServiceServer()
}

func RegisterGameServiceServer(s grpc.ServiceRegistrar, srv GameServiceServer) {
	// If the following call panics, it indicates UnimplementedGameServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GameService_ServiceDesc, srv)
}

func _GameService_CreateGame_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateGameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameServiceServer).CreateGame(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GameService_CreateGame_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameServiceServer).CreateGame(ctx, req.(*CreateGameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GameService_GetGame_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameServiceServer).GetGame(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GameService_GetGame_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameServiceServer).GetGame(ctx, req.(*GetGameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GameService_UpdateGame_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateGameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameServiceServer).UpdateGame(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GameService_UpdateGame_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameServiceServer).UpdateGame(ctx, req.(*UpdateGameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GameService_ListGames_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListGamesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameServiceServer).ListGames(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GameService_ListGames_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameServiceServer).ListGames(ctx, req.(*ListGamesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GameService_DeleteGame_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteGameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameServiceServer).DeleteGame(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GameService_DeleteGame_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameServiceServer).DeleteGame(ctx, req.(*DeleteGameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GameService_ActivateGame_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ActivateGameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameServiceServer).ActivateGame(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GameService_ActivateGame_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameServiceServer).ActivateGame(ctx, req.(*ActivateGameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GameService_SuspendGame_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SuspendGameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameServiceServer).SuspendGame(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GameService_SuspendGame_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameServiceServer).SuspendGame(ctx, req.(*SuspendGameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GameService_CreateGameRules_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateGameRulesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameServiceServer).CreateGameRules(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GameService_CreateGameRules_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameServiceServer).CreateGameRules(ctx, req.(*CreateGameRulesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GameService_GetGameRules_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGameRulesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameServiceServer).GetGameRules(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GameService_GetGameRules_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameServiceServer).GetGameRules(ctx, req.(*GetGameRulesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GameService_UpdateGameRules_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateGameRulesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameServiceServer).UpdateGameRules(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GameService_UpdateGameRules_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameServiceServer).UpdateGameRules(ctx, req.(*UpdateGameRulesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GameService_CreatePrizeStructure_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePrizeStructureRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameServiceServer).CreatePrizeStructure(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GameService_CreatePrizeStructure_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameServiceServer).CreatePrizeStructure(ctx, req.(*CreatePrizeStructureRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GameService_GetPrizeStructure_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPrizeStructureRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameServiceServer).GetPrizeStructure(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GameService_GetPrizeStructure_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameServiceServer).GetPrizeStructure(ctx, req.(*GetPrizeStructureRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GameService_UpdatePrizeStructure_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdatePrizeStructureRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameServiceServer).UpdatePrizeStructure(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GameService_UpdatePrizeStructure_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameServiceServer).UpdatePrizeStructure(ctx, req.(*UpdatePrizeStructureRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GameService_SubmitForApproval_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitForApprovalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameServiceServer).SubmitForApproval(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GameService_SubmitForApproval_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameServiceServer).SubmitForApproval(ctx, req.(*SubmitForApprovalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GameService_ApproveGame_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApproveGameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameServiceServer).ApproveGame(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GameService_ApproveGame_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameServiceServer).ApproveGame(ctx, req.(*ApproveGameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GameService_RejectGame_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RejectGameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameServiceServer).RejectGame(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GameService_RejectGame_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameServiceServer).RejectGame(ctx, req.(*RejectGameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GameService_GetApprovalStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetApprovalStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameServiceServer).GetApprovalStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GameService_GetApprovalStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameServiceServer).GetApprovalStatus(ctx, req.(*GetApprovalStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GameService_GetPendingApprovals_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPendingApprovalsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameServiceServer).GetPendingApprovals(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GameService_GetPendingApprovals_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameServiceServer).GetPendingApprovals(ctx, req.(*GetPendingApprovalsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GameService_ScheduleGame_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ScheduleGameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameServiceServer).ScheduleGame(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GameService_ScheduleGame_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameServiceServer).ScheduleGame(ctx, req.(*ScheduleGameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GameService_GetGameSchedule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGameScheduleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameServiceServer).GetGameSchedule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GameService_GetGameSchedule_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameServiceServer).GetGameSchedule(ctx, req.(*GetGameScheduleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GameService_GetScheduleById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetScheduleByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameServiceServer).GetScheduleById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GameService_GetScheduleById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameServiceServer).GetScheduleById(ctx, req.(*GetScheduleByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GameService_UpdateScheduledGame_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateScheduledGameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameServiceServer).UpdateScheduledGame(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GameService_UpdateScheduledGame_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameServiceServer).UpdateScheduledGame(ctx, req.(*UpdateScheduledGameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GameService_GenerateWeeklySchedule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateWeeklyScheduleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameServiceServer).GenerateWeeklySchedule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GameService_GenerateWeeklySchedule_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameServiceServer).GenerateWeeklySchedule(ctx, req.(*GenerateWeeklyScheduleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GameService_GetWeeklySchedule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWeeklyScheduleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameServiceServer).GetWeeklySchedule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GameService_GetWeeklySchedule_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameServiceServer).GetWeeklySchedule(ctx, req.(*GetWeeklyScheduleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GameService_ClearWeeklySchedule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClearWeeklyScheduleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameServiceServer).ClearWeeklySchedule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GameService_ClearWeeklySchedule_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameServiceServer).ClearWeeklySchedule(ctx, req.(*ClearWeeklyScheduleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GameService_UpdateGameLogo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateGameLogoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameServiceServer).UpdateGameLogo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GameService_UpdateGameLogo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameServiceServer).UpdateGameLogo(ctx, req.(*UpdateGameLogoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GameService_DeleteGameLogo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteGameLogoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameServiceServer).DeleteGameLogo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GameService_DeleteGameLogo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameServiceServer).DeleteGameLogo(ctx, req.(*DeleteGameLogoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GameService_ServiceDesc is the grpc.ServiceDesc for GameService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GameService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "game.v1.GameService",
	HandlerType: (*GameServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateGame",
			Handler:    _GameService_CreateGame_Handler,
		},
		{
			MethodName: "GetGame",
			Handler:    _GameService_GetGame_Handler,
		},
		{
			MethodName: "UpdateGame",
			Handler:    _GameService_UpdateGame_Handler,
		},
		{
			MethodName: "ListGames",
			Handler:    _GameService_ListGames_Handler,
		},
		{
			MethodName: "DeleteGame",
			Handler:    _GameService_DeleteGame_Handler,
		},
		{
			MethodName: "ActivateGame",
			Handler:    _GameService_ActivateGame_Handler,
		},
		{
			MethodName: "SuspendGame",
			Handler:    _GameService_SuspendGame_Handler,
		},
		{
			MethodName: "CreateGameRules",
			Handler:    _GameService_CreateGameRules_Handler,
		},
		{
			MethodName: "GetGameRules",
			Handler:    _GameService_GetGameRules_Handler,
		},
		{
			MethodName: "UpdateGameRules",
			Handler:    _GameService_UpdateGameRules_Handler,
		},
		{
			MethodName: "CreatePrizeStructure",
			Handler:    _GameService_CreatePrizeStructure_Handler,
		},
		{
			MethodName: "GetPrizeStructure",
			Handler:    _GameService_GetPrizeStructure_Handler,
		},
		{
			MethodName: "UpdatePrizeStructure",
			Handler:    _GameService_UpdatePrizeStructure_Handler,
		},
		{
			MethodName: "SubmitForApproval",
			Handler:    _GameService_SubmitForApproval_Handler,
		},
		{
			MethodName: "ApproveGame",
			Handler:    _GameService_ApproveGame_Handler,
		},
		{
			MethodName: "RejectGame",
			Handler:    _GameService_RejectGame_Handler,
		},
		{
			MethodName: "GetApprovalStatus",
			Handler:    _GameService_GetApprovalStatus_Handler,
		},
		{
			MethodName: "GetPendingApprovals",
			Handler:    _GameService_GetPendingApprovals_Handler,
		},
		{
			MethodName: "ScheduleGame",
			Handler:    _GameService_ScheduleGame_Handler,
		},
		{
			MethodName: "GetGameSchedule",
			Handler:    _GameService_GetGameSchedule_Handler,
		},
		{
			MethodName: "GetScheduleById",
			Handler:    _GameService_GetScheduleById_Handler,
		},
		{
			MethodName: "UpdateScheduledGame",
			Handler:    _GameService_UpdateScheduledGame_Handler,
		},
		{
			MethodName: "GenerateWeeklySchedule",
			Handler:    _GameService_GenerateWeeklySchedule_Handler,
		},
		{
			MethodName: "GetWeeklySchedule",
			Handler:    _GameService_GetWeeklySchedule_Handler,
		},
		{
			MethodName: "ClearWeeklySchedule",
			Handler:    _GameService_ClearWeeklySchedule_Handler,
		},
		{
			MethodName: "UpdateGameLogo",
			Handler:    _GameService_UpdateGameLogo_Handler,
		},
		{
			MethodName: "DeleteGameLogo",
			Handler:    _GameService_DeleteGameLogo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/game/v1/game.proto",
}
