// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v5.29.3
// source: proto/ticket/v1/ticket.proto

package ticketv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TicketService_IssueTicket_FullMethodName            = "/ticket.v1.TicketService/IssueTicket"
	TicketService_GetTicket_FullMethodName              = "/ticket.v1.TicketService/GetTicket"
	TicketService_GetTicketBySerial_FullMethodName      = "/ticket.v1.TicketService/GetTicketBySerial"
	TicketService_ListTickets_FullMethodName            = "/ticket.v1.TicketService/ListTickets"
	TicketService_ValidateTicket_FullMethodName         = "/ticket.v1.TicketService/ValidateTicket"
	TicketService_CancelTicket_FullMethodName           = "/ticket.v1.TicketService/CancelTicket"
	TicketService_VoidTicket_FullMethodName             = "/ticket.v1.TicketService/VoidTicket"
	TicketService_ReprintTicket_FullMethodName          = "/ticket.v1.TicketService/ReprintTicket"
	TicketService_CheckWinnings_FullMethodName          = "/ticket.v1.TicketService/CheckWinnings"
	TicketService_UpdateTicketsDrawId_FullMethodName    = "/ticket.v1.TicketService/UpdateTicketsDrawId"
	TicketService_MarkTicketAsPaid_FullMethodName       = "/ticket.v1.TicketService/MarkTicketAsPaid"
	TicketService_UpdateTicketStatus_FullMethodName     = "/ticket.v1.TicketService/UpdateTicketStatus"
	TicketService_UpdateTicketStatuses_FullMethodName   = "/ticket.v1.TicketService/UpdateTicketStatuses"
	TicketService_GetDailyMetrics_FullMethodName        = "/ticket.v1.TicketService/GetDailyMetrics"
	TicketService_GetMonthlyMetrics_FullMethodName      = "/ticket.v1.TicketService/GetMonthlyMetrics"
	TicketService_GetTopPerformingAgents_FullMethodName = "/ticket.v1.TicketService/GetTopPerformingAgents"
	TicketService_GetAllTicketsForDraw_FullMethodName   = "/ticket.v1.TicketService/GetAllTicketsForDraw"
)

// TicketServiceClient is the client API for TicketService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// TicketService defines the gRPC service for ticket management
type TicketServiceClient interface {
	// IssueTicket creates a new lottery ticket
	IssueTicket(ctx context.Context, in *IssueTicketRequest, opts ...grpc.CallOption) (*IssueTicketResponse, error)
	// GetTicket retrieves a ticket by ID
	GetTicket(ctx context.Context, in *GetTicketRequest, opts ...grpc.CallOption) (*GetTicketResponse, error)
	// GetTicketBySerial retrieves a ticket by serial number
	GetTicketBySerial(ctx context.Context, in *GetTicketBySerialRequest, opts ...grpc.CallOption) (*GetTicketBySerialResponse, error)
	// ListTickets retrieves a paginated list of tickets with optional filters
	ListTickets(ctx context.Context, in *ListTicketsRequest, opts ...grpc.CallOption) (*ListTicketsResponse, error)
	// ValidateTicket marks a ticket as validated and checks for winnings
	ValidateTicket(ctx context.Context, in *ValidateTicketRequest, opts ...grpc.CallOption) (*ValidateTicketResponse, error)
	// CancelTicket cancels a ticket before validation
	CancelTicket(ctx context.Context, in *CancelTicketRequest, opts ...grpc.CallOption) (*CancelTicketResponse, error)
	// VoidTicket voids a ticket (administrative action)
	VoidTicket(ctx context.Context, in *VoidTicketRequest, opts ...grpc.CallOption) (*VoidTicketResponse, error)
	// ReprintTicket generates a reprint of an existing ticket
	ReprintTicket(ctx context.Context, in *ReprintTicketRequest, opts ...grpc.CallOption) (*ReprintTicketResponse, error)
	// CheckWinnings checks if a ticket has winnings without validating
	CheckWinnings(ctx context.Context, in *CheckWinningsRequest, opts ...grpc.CallOption) (*CheckWinningsResponse, error)
	// UpdateTicketsDrawId updates all tickets for a game schedule with a draw ID
	UpdateTicketsDrawId(ctx context.Context, in *UpdateTicketsDrawIdRequest, opts ...grpc.CallOption) (*UpdateTicketsDrawIdResponse, error)
	// MarkTicketAsPaid marks a winning ticket as paid
	MarkTicketAsPaid(ctx context.Context, in *MarkTicketAsPaidRequest, opts ...grpc.CallOption) (*MarkTicketAsPaidResponse, error)
	// UpdateTicketStatus updates a ticket's status after draw processing (won/lost)
	UpdateTicketStatus(ctx context.Context, in *UpdateTicketStatusRequest, opts ...grpc.CallOption) (*UpdateTicketStatusResponse, error)
	// UpdateTicketStatuses updates multiple tickets' statuses in a single batch operation
	// This is optimized for draw processing to avoid N+1 query problems
	UpdateTicketStatuses(ctx context.Context, in *UpdateTicketStatusesRequest, opts ...grpc.CallOption) (*UpdateTicketStatusesResponse, error)
	// GetDailyMetrics returns daily metrics for dashboard analytics
	GetDailyMetrics(ctx context.Context, in *GetDailyMetricsRequest, opts ...grpc.CallOption) (*GetDailyMetricsResponse, error)
	// GetMonthlyMetrics returns monthly aggregated metrics for charts
	GetMonthlyMetrics(ctx context.Context, in *GetMonthlyMetricsRequest, opts ...grpc.CallOption) (*GetMonthlyMetricsResponse, error)
	// GetTopPerformingAgents retrieves top performing agents by revenue
	GetTopPerformingAgents(ctx context.Context, in *GetTopPerformingAgentsRequest, opts ...grpc.CallOption) (*GetTopPerformingAgentsResponse, error)
	// GetAllTicketsForDraw retrieves all tickets for a specific draw without pagination limits
	// This is specifically for internal service-to-service calls (e.g., draw processing)
	GetAllTicketsForDraw(ctx context.Context, in *GetAllTicketsForDrawRequest, opts ...grpc.CallOption) (*GetAllTicketsForDrawResponse, error)
}

type ticketServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTicketServiceClient(cc grpc.ClientConnInterface) TicketServiceClient {
	return &ticketServiceClient{cc}
}

func (c *ticketServiceClient) IssueTicket(ctx context.Context, in *IssueTicketRequest, opts ...grpc.CallOption) (*IssueTicketResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IssueTicketResponse)
	err := c.cc.Invoke(ctx, TicketService_IssueTicket_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ticketServiceClient) GetTicket(ctx context.Context, in *GetTicketRequest, opts ...grpc.CallOption) (*GetTicketResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTicketResponse)
	err := c.cc.Invoke(ctx, TicketService_GetTicket_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ticketServiceClient) GetTicketBySerial(ctx context.Context, in *GetTicketBySerialRequest, opts ...grpc.CallOption) (*GetTicketBySerialResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTicketBySerialResponse)
	err := c.cc.Invoke(ctx, TicketService_GetTicketBySerial_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ticketServiceClient) ListTickets(ctx context.Context, in *ListTicketsRequest, opts ...grpc.CallOption) (*ListTicketsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListTicketsResponse)
	err := c.cc.Invoke(ctx, TicketService_ListTickets_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ticketServiceClient) ValidateTicket(ctx context.Context, in *ValidateTicketRequest, opts ...grpc.CallOption) (*ValidateTicketResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ValidateTicketResponse)
	err := c.cc.Invoke(ctx, TicketService_ValidateTicket_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ticketServiceClient) CancelTicket(ctx context.Context, in *CancelTicketRequest, opts ...grpc.CallOption) (*CancelTicketResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CancelTicketResponse)
	err := c.cc.Invoke(ctx, TicketService_CancelTicket_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ticketServiceClient) VoidTicket(ctx context.Context, in *VoidTicketRequest, opts ...grpc.CallOption) (*VoidTicketResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VoidTicketResponse)
	err := c.cc.Invoke(ctx, TicketService_VoidTicket_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ticketServiceClient) ReprintTicket(ctx context.Context, in *ReprintTicketRequest, opts ...grpc.CallOption) (*ReprintTicketResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReprintTicketResponse)
	err := c.cc.Invoke(ctx, TicketService_ReprintTicket_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ticketServiceClient) CheckWinnings(ctx context.Context, in *CheckWinningsRequest, opts ...grpc.CallOption) (*CheckWinningsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckWinningsResponse)
	err := c.cc.Invoke(ctx, TicketService_CheckWinnings_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ticketServiceClient) UpdateTicketsDrawId(ctx context.Context, in *UpdateTicketsDrawIdRequest, opts ...grpc.CallOption) (*UpdateTicketsDrawIdResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateTicketsDrawIdResponse)
	err := c.cc.Invoke(ctx, TicketService_UpdateTicketsDrawId_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ticketServiceClient) MarkTicketAsPaid(ctx context.Context, in *MarkTicketAsPaidRequest, opts ...grpc.CallOption) (*MarkTicketAsPaidResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MarkTicketAsPaidResponse)
	err := c.cc.Invoke(ctx, TicketService_MarkTicketAsPaid_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ticketServiceClient) UpdateTicketStatus(ctx context.Context, in *UpdateTicketStatusRequest, opts ...grpc.CallOption) (*UpdateTicketStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateTicketStatusResponse)
	err := c.cc.Invoke(ctx, TicketService_UpdateTicketStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ticketServiceClient) UpdateTicketStatuses(ctx context.Context, in *UpdateTicketStatusesRequest, opts ...grpc.CallOption) (*UpdateTicketStatusesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateTicketStatusesResponse)
	err := c.cc.Invoke(ctx, TicketService_UpdateTicketStatuses_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ticketServiceClient) GetDailyMetrics(ctx context.Context, in *GetDailyMetricsRequest, opts ...grpc.CallOption) (*GetDailyMetricsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDailyMetricsResponse)
	err := c.cc.Invoke(ctx, TicketService_GetDailyMetrics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ticketServiceClient) GetMonthlyMetrics(ctx context.Context, in *GetMonthlyMetricsRequest, opts ...grpc.CallOption) (*GetMonthlyMetricsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMonthlyMetricsResponse)
	err := c.cc.Invoke(ctx, TicketService_GetMonthlyMetrics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ticketServiceClient) GetTopPerformingAgents(ctx context.Context, in *GetTopPerformingAgentsRequest, opts ...grpc.CallOption) (*GetTopPerformingAgentsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTopPerformingAgentsResponse)
	err := c.cc.Invoke(ctx, TicketService_GetTopPerformingAgents_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ticketServiceClient) GetAllTicketsForDraw(ctx context.Context, in *GetAllTicketsForDrawRequest, opts ...grpc.CallOption) (*GetAllTicketsForDrawResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAllTicketsForDrawResponse)
	err := c.cc.Invoke(ctx, TicketService_GetAllTicketsForDraw_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TicketServiceServer is the server API for TicketService service.
// All implementations should embed UnimplementedTicketServiceServer
// for forward compatibility.
//
// TicketService defines the gRPC service for ticket management
type TicketServiceServer interface {
	// IssueTicket creates a new lottery ticket
	IssueTicket(context.Context, *IssueTicketRequest) (*IssueTicketResponse, error)
	// GetTicket retrieves a ticket by ID
	GetTicket(context.Context, *GetTicketRequest) (*GetTicketResponse, error)
	// GetTicketBySerial retrieves a ticket by serial number
	GetTicketBySerial(context.Context, *GetTicketBySerialRequest) (*GetTicketBySerialResponse, error)
	// ListTickets retrieves a paginated list of tickets with optional filters
	ListTickets(context.Context, *ListTicketsRequest) (*ListTicketsResponse, error)
	// ValidateTicket marks a ticket as validated and checks for winnings
	ValidateTicket(context.Context, *ValidateTicketRequest) (*ValidateTicketResponse, error)
	// CancelTicket cancels a ticket before validation
	CancelTicket(context.Context, *CancelTicketRequest) (*CancelTicketResponse, error)
	// VoidTicket voids a ticket (administrative action)
	VoidTicket(context.Context, *VoidTicketRequest) (*VoidTicketResponse, error)
	// ReprintTicket generates a reprint of an existing ticket
	ReprintTicket(context.Context, *ReprintTicketRequest) (*ReprintTicketResponse, error)
	// CheckWinnings checks if a ticket has winnings without validating
	CheckWinnings(context.Context, *CheckWinningsRequest) (*CheckWinningsResponse, error)
	// UpdateTicketsDrawId updates all tickets for a game schedule with a draw ID
	UpdateTicketsDrawId(context.Context, *UpdateTicketsDrawIdRequest) (*UpdateTicketsDrawIdResponse, error)
	// MarkTicketAsPaid marks a winning ticket as paid
	MarkTicketAsPaid(context.Context, *MarkTicketAsPaidRequest) (*MarkTicketAsPaidResponse, error)
	// UpdateTicketStatus updates a ticket's status after draw processing (won/lost)
	UpdateTicketStatus(context.Context, *UpdateTicketStatusRequest) (*UpdateTicketStatusResponse, error)
	// UpdateTicketStatuses updates multiple tickets' statuses in a single batch operation
	// This is optimized for draw processing to avoid N+1 query problems
	UpdateTicketStatuses(context.Context, *UpdateTicketStatusesRequest) (*UpdateTicketStatusesResponse, error)
	// GetDailyMetrics returns daily metrics for dashboard analytics
	GetDailyMetrics(context.Context, *GetDailyMetricsRequest) (*GetDailyMetricsResponse, error)
	// GetMonthlyMetrics returns monthly aggregated metrics for charts
	GetMonthlyMetrics(context.Context, *GetMonthlyMetricsRequest) (*GetMonthlyMetricsResponse, error)
	// GetTopPerformingAgents retrieves top performing agents by revenue
	GetTopPerformingAgents(context.Context, *GetTopPerformingAgentsRequest) (*GetTopPerformingAgentsResponse, error)
	// GetAllTicketsForDraw retrieves all tickets for a specific draw without pagination limits
	// This is specifically for internal service-to-service calls (e.g., draw processing)
	GetAllTicketsForDraw(context.Context, *GetAllTicketsForDrawRequest) (*GetAllTicketsForDrawResponse, error)
}

// UnimplementedTicketServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTicketServiceServer struct{}

func (UnimplementedTicketServiceServer) IssueTicket(context.Context, *IssueTicketRequest) (*IssueTicketResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method IssueTicket not implemented")
}
func (UnimplementedTicketServiceServer) GetTicket(context.Context, *GetTicketRequest) (*GetTicketResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTicket not implemented")
}
func (UnimplementedTicketServiceServer) GetTicketBySerial(context.Context, *GetTicketBySerialRequest) (*GetTicketBySerialResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTicketBySerial not implemented")
}
func (UnimplementedTicketServiceServer) ListTickets(context.Context, *ListTicketsRequest) (*ListTicketsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListTickets not implemented")
}
func (UnimplementedTicketServiceServer) ValidateTicket(context.Context, *ValidateTicketRequest) (*ValidateTicketResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ValidateTicket not implemented")
}
func (UnimplementedTicketServiceServer) CancelTicket(context.Context, *CancelTicketRequest) (*CancelTicketResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CancelTicket not implemented")
}
func (UnimplementedTicketServiceServer) VoidTicket(context.Context, *VoidTicketRequest) (*VoidTicketResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method VoidTicket not implemented")
}
func (UnimplementedTicketServiceServer) ReprintTicket(context.Context, *ReprintTicketRequest) (*ReprintTicketResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReprintTicket not implemented")
}
func (UnimplementedTicketServiceServer) CheckWinnings(context.Context, *CheckWinningsRequest) (*CheckWinningsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckWinnings not implemented")
}
func (UnimplementedTicketServiceServer) UpdateTicketsDrawId(context.Context, *UpdateTicketsDrawIdRequest) (*UpdateTicketsDrawIdResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateTicketsDrawId not implemented")
}
func (UnimplementedTicketServiceServer) MarkTicketAsPaid(context.Context, *MarkTicketAsPaidRequest) (*MarkTicketAsPaidResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method MarkTicketAsPaid not implemented")
}
func (UnimplementedTicketServiceServer) UpdateTicketStatus(context.Context, *UpdateTicketStatusRequest) (*UpdateTicketStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateTicketStatus not implemented")
}
func (UnimplementedTicketServiceServer) UpdateTicketStatuses(context.Context, *UpdateTicketStatusesRequest) (*UpdateTicketStatusesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateTicketStatuses not implemented")
}
func (UnimplementedTicketServiceServer) GetDailyMetrics(context.Context, *GetDailyMetricsRequest) (*GetDailyMetricsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDailyMetrics not implemented")
}
func (UnimplementedTicketServiceServer) GetMonthlyMetrics(context.Context, *GetMonthlyMetricsRequest) (*GetMonthlyMetricsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMonthlyMetrics not implemented")
}
func (UnimplementedTicketServiceServer) GetTopPerformingAgents(context.Context, *GetTopPerformingAgentsRequest) (*GetTopPerformingAgentsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTopPerformingAgents not implemented")
}
func (UnimplementedTicketServiceServer) GetAllTicketsForDraw(context.Context, *GetAllTicketsForDrawRequest) (*GetAllTicketsForDrawResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAllTicketsForDraw not implemented")
}
func (UnimplementedTicketServiceServer) testEmbeddedByValue() {}

// UnsafeTicketServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TicketServiceServer will
// result in compilation errors.
type UnsafeTicketServiceServer interface {
	mustEmbedUnimplementedTicketServiceServer()
}

func RegisterTicketServiceServer(s grpc.ServiceRegistrar, srv TicketServiceServer) {
	// If the following call panics, it indicates UnimplementedTicketServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TicketService_ServiceDesc, srv)
}

func _TicketService_IssueTicket_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IssueTicketRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TicketServiceServer).IssueTicket(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TicketService_IssueTicket_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TicketServiceServer).IssueTicket(ctx, req.(*IssueTicketRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TicketService_GetTicket_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTicketRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TicketServiceServer).GetTicket(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TicketService_GetTicket_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TicketServiceServer).GetTicket(ctx, req.(*GetTicketRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TicketService_GetTicketBySerial_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTicketBySerialRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TicketServiceServer).GetTicketBySerial(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TicketService_GetTicketBySerial_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TicketServiceServer).GetTicketBySerial(ctx, req.(*GetTicketBySerialRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TicketService_ListTickets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTicketsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TicketServiceServer).ListTickets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TicketService_ListTickets_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TicketServiceServer).ListTickets(ctx, req.(*ListTicketsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TicketService_ValidateTicket_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateTicketRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TicketServiceServer).ValidateTicket(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TicketService_ValidateTicket_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TicketServiceServer).ValidateTicket(ctx, req.(*ValidateTicketRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TicketService_CancelTicket_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelTicketRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TicketServiceServer).CancelTicket(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TicketService_CancelTicket_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TicketServiceServer).CancelTicket(ctx, req.(*CancelTicketRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TicketService_VoidTicket_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VoidTicketRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TicketServiceServer).VoidTicket(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TicketService_VoidTicket_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TicketServiceServer).VoidTicket(ctx, req.(*VoidTicketRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TicketService_ReprintTicket_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReprintTicketRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TicketServiceServer).ReprintTicket(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TicketService_ReprintTicket_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TicketServiceServer).ReprintTicket(ctx, req.(*ReprintTicketRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TicketService_CheckWinnings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckWinningsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TicketServiceServer).CheckWinnings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TicketService_CheckWinnings_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TicketServiceServer).CheckWinnings(ctx, req.(*CheckWinningsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TicketService_UpdateTicketsDrawId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateTicketsDrawIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TicketServiceServer).UpdateTicketsDrawId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TicketService_UpdateTicketsDrawId_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TicketServiceServer).UpdateTicketsDrawId(ctx, req.(*UpdateTicketsDrawIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TicketService_MarkTicketAsPaid_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MarkTicketAsPaidRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TicketServiceServer).MarkTicketAsPaid(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TicketService_MarkTicketAsPaid_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TicketServiceServer).MarkTicketAsPaid(ctx, req.(*MarkTicketAsPaidRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TicketService_UpdateTicketStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateTicketStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TicketServiceServer).UpdateTicketStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TicketService_UpdateTicketStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TicketServiceServer).UpdateTicketStatus(ctx, req.(*UpdateTicketStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TicketService_UpdateTicketStatuses_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateTicketStatusesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TicketServiceServer).UpdateTicketStatuses(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TicketService_UpdateTicketStatuses_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TicketServiceServer).UpdateTicketStatuses(ctx, req.(*UpdateTicketStatusesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TicketService_GetDailyMetrics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDailyMetricsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TicketServiceServer).GetDailyMetrics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TicketService_GetDailyMetrics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TicketServiceServer).GetDailyMetrics(ctx, req.(*GetDailyMetricsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TicketService_GetMonthlyMetrics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMonthlyMetricsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TicketServiceServer).GetMonthlyMetrics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TicketService_GetMonthlyMetrics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TicketServiceServer).GetMonthlyMetrics(ctx, req.(*GetMonthlyMetricsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TicketService_GetTopPerformingAgents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTopPerformingAgentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TicketServiceServer).GetTopPerformingAgents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TicketService_GetTopPerformingAgents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TicketServiceServer).GetTopPerformingAgents(ctx, req.(*GetTopPerformingAgentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TicketService_GetAllTicketsForDraw_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllTicketsForDrawRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TicketServiceServer).GetAllTicketsForDraw(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TicketService_GetAllTicketsForDraw_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TicketServiceServer).GetAllTicketsForDraw(ctx, req.(*GetAllTicketsForDrawRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TicketService_ServiceDesc is the grpc.ServiceDesc for TicketService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TicketService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ticket.v1.TicketService",
	HandlerType: (*TicketServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "IssueTicket",
			Handler:    _TicketService_IssueTicket_Handler,
		},
		{
			MethodName: "GetTicket",
			Handler:    _TicketService_GetTicket_Handler,
		},
		{
			MethodName: "GetTicketBySerial",
			Handler:    _TicketService_GetTicketBySerial_Handler,
		},
		{
			MethodName: "ListTickets",
			Handler:    _TicketService_ListTickets_Handler,
		},
		{
			MethodName: "ValidateTicket",
			Handler:    _TicketService_ValidateTicket_Handler,
		},
		{
			MethodName: "CancelTicket",
			Handler:    _TicketService_CancelTicket_Handler,
		},
		{
			MethodName: "VoidTicket",
			Handler:    _TicketService_VoidTicket_Handler,
		},
		{
			MethodName: "ReprintTicket",
			Handler:    _TicketService_ReprintTicket_Handler,
		},
		{
			MethodName: "CheckWinnings",
			Handler:    _TicketService_CheckWinnings_Handler,
		},
		{
			MethodName: "UpdateTicketsDrawId",
			Handler:    _TicketService_UpdateTicketsDrawId_Handler,
		},
		{
			MethodName: "MarkTicketAsPaid",
			Handler:    _TicketService_MarkTicketAsPaid_Handler,
		},
		{
			MethodName: "UpdateTicketStatus",
			Handler:    _TicketService_UpdateTicketStatus_Handler,
		},
		{
			MethodName: "UpdateTicketStatuses",
			Handler:    _TicketService_UpdateTicketStatuses_Handler,
		},
		{
			MethodName: "GetDailyMetrics",
			Handler:    _TicketService_GetDailyMetrics_Handler,
		},
		{
			MethodName: "GetMonthlyMetrics",
			Handler:    _TicketService_GetMonthlyMetrics_Handler,
		},
		{
			MethodName: "GetTopPerformingAgents",
			Handler:    _TicketService_GetTopPerformingAgents_Handler,
		},
		{
			MethodName: "GetAllTicketsForDraw",
			Handler:    _TicketService_GetAllTicketsForDraw_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/ticket/v1/ticket.proto",
}
