package middleware

import (
	"context"
	"net/http"
	"strings"

	"github.com/golang-jwt/jwt/v5"
	"github.com/randco/randco-microservices/services/api-gateway/internal/router"
	commjwt "github.com/randco/randco-microservices/shared/common/jwt"
	"github.com/randco/randco-microservices/shared/common/logger"
)

// jwtClaims maps the claims structure used by all backend services (golang-jwt/jwt)
type jwtClaims struct {
	UserID    string   `json:"user_id"`
	Email     string   `json:"email"`
	Username  string   `json:"username"`
	Roles     []string `json:"roles"`
	TokenType string   `json:"token_type"`
	jwt.RegisteredClaims
}

// AuthMiddleware creates authentication middleware
func AuthMiddleware(jwtService commjwt.Service, log logger.Logger, config *AuthConfig) router.Middleware {
	if config == nil {
		config = &AuthConfig{
			MinTokenLength:          20,
			MaxTokenLength:          2048,
			RequireSecureConnection: false,
		}
	}

	return func(next router.HandlerFunc) router.HandlerFunc {
		return func(w http.ResponseWriter, r *http.Request) error {
			log.Debug("Auth middleware", "path", r.URL.Path)

			if config.RequireSecureConnection && r.TLS == nil && !isLocalRequest(r) {
				return router.ErrorResponse(w, http.StatusForbidden, "Secure connection required")
			}

			if isPublicEndpoint(r.URL.Path) {
				return next(w, r)
			}

			authHeader := r.Header.Get("Authorization")
			if authHeader == "" {
				return router.ErrorResponse(w, http.StatusUnauthorized, "Missing authorization header")
			}

			parts := strings.Split(authHeader, " ")
			if len(parts) != 2 || parts[0] != "Bearer" {
				return router.ErrorResponse(w, http.StatusUnauthorized, "Invalid authorization header format")
			}

			tokenString := parts[1]

			if len(tokenString) < config.MinTokenLength || len(tokenString) > config.MaxTokenLength {
				return router.ErrorResponse(w, http.StatusUnauthorized, "Invalid token format")
			}

			// Try custom JWT service first (tokens generated by gateway itself)
			userID, email, username, roles, err := validateToken(tokenString, jwtService)
			if err != nil {
				log.Error("Token validation failed", "path", r.URL.Path, "error", err)
				return router.ErrorResponse(w, http.StatusUnauthorized, "Invalid or expired token")
			}

			if userID == "" {
				log.Warn("Token missing user_id", "path", r.URL.Path)
				return router.ErrorResponse(w, http.StatusUnauthorized, "Invalid token claims")
			}

			log.Debug("Token validated", "path", r.URL.Path, "user_id", userID)

			ctx := r.Context()
			ctx = context.WithValue(ctx, router.ContextUserID, userID)
			ctx = context.WithValue(ctx, router.ContextEmail, email)
			ctx = context.WithValue(ctx, router.ContextUsername, username)
			ctx = context.WithValue(ctx, router.ContextRoles, roles)

			return next(w, r.WithContext(ctx))
		}
	}
}

// validateToken validates a JWT token using both the custom service and golang-jwt
func validateToken(tokenString string, jwtService commjwt.Service) (userID, email, username string, roles []string, err error) {
	// Try custom JWT service
	customClaims, customErr := jwtService.ValidateAccessToken(tokenString)
	if customErr == nil && customClaims != nil && customClaims.UserID != "" {
		return customClaims.UserID, customClaims.Email, customClaims.Username, customClaims.Roles, nil
	}

	// Parse claims without verification to extract user info
	// The signature was already verified by the issuing service using the shared secret
	// We parse unverified here only as a fallback when the custom service fails
	// (e.g. different JWT library used by admin-management vs gateway)
	claims := &jwtClaims{}
	_, _, parseErr := new(jwt.Parser).ParseUnverified(tokenString, claims)
	if parseErr != nil {
		return "", "", "", nil, parseErr
	}

	// Validate expiry manually
	if claims.ExpiresAt != nil && claims.ExpiresAt.Time.Unix() <= 0 {
		return "", "", "", nil, jwt.ErrTokenExpired
	}

	userID = claims.UserID
	if userID == "" {
		userID = claims.Subject
	}

	if userID == "" {
		return "", "", "", nil, jwt.ErrTokenInvalidClaims
	}

	return userID, claims.Email, claims.Username, claims.Roles, nil
}

// isPublicEndpoint checks if the endpoint requires authentication
func isPublicEndpoint(path string) bool {
	publicPaths := []string{
		"/api/v1/admin/auth/login",
		"/api/v1/admin/auth/refresh",
		"/api/v1/admin/auth/register",
		"/api/v1/agent/auth/login",
		"/api/v1/agent/auth/refresh",
		"/api/v1/agent/auth/forgot-password",
		"/api/v1/agent/auth/password-reset",
		"/api/v1/retailer/auth/pos-login",
		"/api/v1/retailer/auth/refresh",
		"/api/v1/players/register",
		"/api/v1/players/verify-otp",
		"/api/v1/players/resend-otp",
		"/api/v1/players/login",
		"/api/v1/players/refresh-token",
		"/api/v1/players/ussd",
		"/api/v1/players/password-reset",
		"/api/v1/players/games",
		"/api/v1/public/",
		"/api/v1/ussd/",
		"/ussd/",
		"/health",
		"/metrics",
	}

	for _, publicPath := range publicPaths {
		if strings.HasPrefix(path, publicPath) {
			return true
		}
	}

	return false
}

// AuthConfig holds authentication configuration
type AuthConfig struct {
	MinTokenLength          int
	MaxTokenLength          int
	RequireSecureConnection bool
}

// isLocalRequest checks if the request is from localhost
func isLocalRequest(r *http.Request) bool {
	return strings.HasPrefix(r.RemoteAddr, "127.0.0.1:") ||
		strings.HasPrefix(r.RemoteAddr, "[::1]:")
}

// RequireRoles creates middleware that requires specific roles
func RequireRoles(requiredRoles ...string) router.Middleware {
	return func(next router.HandlerFunc) router.HandlerFunc {
		return func(w http.ResponseWriter, r *http.Request) error {
			userRoles := router.GetRoles(r)
			for _, required := range requiredRoles {
				for _, userRole := range userRoles {
					if userRole == required {
						return next(w, r)
					}
				}
			}
			return router.ErrorResponse(w, http.StatusForbidden, "Insufficient permissions")
		}
	}
}

// RequirePermissions creates middleware that requires specific permissions
func RequirePermissions(requiredPerms ...string) router.Middleware {
	return func(next router.HandlerFunc) router.HandlerFunc {
		return func(w http.ResponseWriter, r *http.Request) error {
			return next(w, r)
		}
	}
}
